package com.fourthskyinteractive.dx4j.windows;

import java.util.HashMap;
import java.util.Map;

public class WindowsException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8785991875414909443L;
	
	// Error codes
	public static final long	E_INVALIDARG												= 0x80070057;
	public static final long    UI_E_CREATE_FAILED											= 0x802A0001;
	public static final long    UI_E_SHUTDOWN_CALLED										= 0x802A0002;
	public static final long    UI_E_ILLEGAL_REENTRANCY										= 0x802A0003;
	public static final long    UI_E_OBJECT_SEALED											= 0x802A0004;
	public static final long    UI_E_VALUE_NOT_SET											= 0x802A0005;
	public static final long    UI_E_VALUE_NOT_DETERMINED									= 0x802A0006;
	public static final long    UI_E_INVALID_OUTPUT											= 0x802A0007;
	public static final long    UI_E_BOOLEAN_EXPECTED										= 0x802A0008;
	public static final long    UI_E_DIFFERENT_OWNER										= 0x802A0009;
	public static final long    UI_E_AMBIGUOUS_MATCH										= 0x802A000A;
	public static final long    UI_E_FP_OVERFLOW											= 0x802A000B;
	public static final long    UI_E_WRONG_THREAD											= 0x802A000C;
	public static final long    UI_E_STORYBOARD_ACTIVE										= 0x802A0101;
	public static final long    UI_E_STORYBOARD_NOT_PLAYING									= 0x802A0102;
	public static final long    UI_E_START_KEYFRAME_AFTER_END								= 0x802A0103;
	public static final long    UI_E_END_KEYFRAME_NOT_DETERMINED							= 0x802A0104;
	public static final long    UI_E_LOOPS_OVERLAP											= 0x802A0105;
	public static final long    UI_E_TRANSITION_ALREADY_USED								= 0x802A0106;
	public static final long    UI_E_TRANSITION_NOT_IN_STORYBOARD							= 0x802A0107;
	public static final long    UI_E_TRANSITION_ECLIPSED									= 0x802A0108;
	public static final long    UI_E_TIME_BEFORE_LAST_UPDATE								= 0x802A0109;
	public static final long    UI_E_TIMER_CLIENT_ALREADY_CONNECTED							= 0x802A010A;
	public static final long    UI_E_INVALID_DIMENSION										= 0x802A010B;
	public static final long    UI_E_PRIMITIVE_OUT_OF_BOUNDS								= 0x802A010C;
	public static final long    UI_E_WINDOW_CLOSED											= 0x802A0201;
	public static final long    E_AUDIO_ENGINE_NODE_NOT_FOUND								= 0x80660001;
	public static final long    D3DERR_INVALIDCALL                                          = 0x8876086C;
    public static final long    DXGI_STATUS_OCCLUDED										= 0x087A0001;
	public static final long    DXGI_STATUS_CLIPPED											= 0x087A0002;
	public static final long    DXGI_STATUS_NO_REDIRECTION									= 0x087A0004;
	public static final long    DXGI_STATUS_NO_DESKTOP_ACCESS								= 0x087A0005;
	public static final long    DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE					= 0x087A0006;
	public static final long    DXGI_STATUS_MODE_CHANGED									= 0x087A0007;
	public static final long    DXGI_STATUS_MODE_CHANGE_IN_PROGRESS							= 0x087A0008;
	public static final long    DXGI_ERROR_INVALID_CALL										= 0x887A0001;
	public static final long    DXGI_ERROR_NOT_FOUND										= 0x887A0002;
	public static final long    DXGI_ERROR_MORE_DATA										= 0x887A0003;
	public static final long    DXGI_ERROR_UNSUPPORTED										= 0x887A0004;
	public static final long    DXGI_ERROR_DEVICE_REMOVED									= 0x887A0005;
	public static final long    DXGI_ERROR_DEVICE_HUNG										= 0x887A0006;
	public static final long    DXGI_ERROR_DEVICE_RESET										= 0x887A0007;
	public static final long    DXGI_ERROR_WAS_STILL_DRAWING								= 0x887A000A;
	public static final long    DXGI_ERROR_FRAME_STATISTICS_DISJOINT						= 0x887A000B;
	public static final long    DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE						= 0x887A000C;
	public static final long    DXGI_ERROR_DRIVER_INTERNAL_ERROR							= 0x887A0020;
	public static final long    DXGI_ERROR_NONEXCLUSIVE										= 0x887A0021;
	public static final long    DXGI_ERROR_NOT_CURRENTLY_AVAILABLE							= 0x887A0022;
	public static final long    DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED						= 0x887A0023;
	public static final long    DXGI_ERROR_REMOTE_OUTOFMEMORY								= 0x887A0024;
	public static final long    DXGI_ERROR_ACCESS_LOST										= 0x887A0026;
	public static final long    DXGI_ERROR_WAIT_TIMEOUT										= 0x887A0027;
	public static final long    DXGI_ERROR_SESSION_DISCONNECTED								= 0x887A0028;
	public static final long    DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE							= 0x887A0029;
	public static final long    DXGI_ERROR_CANNOT_PROTECT_CONTENT							= 0x887A002A;
	public static final long    DXGI_ERROR_ACCESS_DENIED									= 0x887A002B;
	public static final long    DXGI_STATUS_UNOCCLUDED										= 0x087A0009;
	public static final long    DXGI_STATUS_DDA_WAS_STILL_DRAWING							= 0x087A000A;
	public static final long    DXGI_ERROR_MODE_CHANGE_IN_PROGRESS							= 0x887A0025;
	public static final long    DXGI_DDI_ERR_WASSTILLDRAWING								= 0x887B0001;
	public static final long    DXGI_DDI_ERR_UNSUPPORTED									= 0x887B0002;
	public static final long    DXGI_DDI_ERR_NONEXCLUSIVE									= 0x887B0003;
	public static final long    D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS					= 0x88790001;
	public static final long    D3D10_ERROR_FILE_NOT_FOUND									= 0x88790002;
	public static final long    D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS					= 0x887C0001;
	public static final long    D3D11_ERROR_FILE_NOT_FOUND									= 0x887C0002;
	public static final long    D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS					= 0x887C0003;
	public static final long    D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD	= 0x887C0004;
	public static final long    D2DERR_WRONG_STATE											= 0x88990001;
	public static final long    D2DERR_NOT_INITIALIZED										= 0x88990002;
	public static final long    D2DERR_UNSUPPORTED_OPERATION								= 0x88990003;
	public static final long    D2DERR_SCANNER_FAILED										= 0x88990004;
	public static final long    D2DERR_SCREEN_ACCESS_DENIED									= 0x88990005;
	public static final long    D2DERR_DISPLAY_STATE_INVALID								= 0x88990006;
	public static final long    D2DERR_ZERO_VECTOR											= 0x88990007;
	public static final long    D2DERR_INTERNAL_ERROR										= 0x88990008;
	public static final long    D2DERR_DISPLAY_FORMAT_NOT_SUPPORTED							= 0x88990009;
	public static final long    D2DERR_INVALID_CALL											= 0x8899000A;
	public static final long    D2DERR_NO_HARDWARE_DEVICE									= 0x8899000B;
	public static final long    D2DERR_RECREATE_TARGET										= 0x8899000C;
	public static final long    D2DERR_TOO_MANY_SHADER_ELEMENTS								= 0x8899000D;
	public static final long    D2DERR_SHADER_COMPILE_FAILED								= 0x8899000E;
	public static final long    D2DERR_MAX_TEXTURE_SIZE_EXCEEDED							= 0x8899000F;
	public static final long    D2DERR_UNSUPPORTED_VERSION									= 0x88990010;
	public static final long    D2DERR_BAD_NUMBER											= 0x88990011;
	public static final long    D2DERR_WRONG_FACTORY										= 0x88990012;
	public static final long    D2DERR_LAYER_ALREADY_IN_USE									= 0x88990013;
	public static final long    D2DERR_POP_CALL_DID_NOT_MATCH_PUSH							= 0x88990014;
	public static final long    D2DERR_WRONG_RESOURCE_DOMAIN								= 0x88990015;
	public static final long    D2DERR_PUSH_POP_UNBALANCED									= 0x88990016;
	public static final long    D2DERR_RENDER_TARGET_HAS_LAYER_OR_CLIPRECT					= 0x88990017;
	public static final long    D2DERR_INCOMPATIBLE_BRUSH_TYPES								= 0x88990018;
	public static final long    D2DERR_WIN32_ERROR											= 0x88990019;
	public static final long    D2DERR_TARGET_NOT_GDI_COMPATIBLE							= 0x8899001A;
	public static final long    D2DERR_TEXT_EFFECT_IS_WRONG_TYPE							= 0x8899001B;
	public static final long    D2DERR_TEXT_RENDERER_NOT_RELEASED							= 0x8899001C;
	public static final long    D2DERR_EXCEEDS_MAX_BITMAP_SIZE								= 0x8899001D;
	public static final long    D2DERR_INVALID_GRAPH_CONFIGURATION							= 0x8899001E;
	public static final long    D2DERR_INVALID_INTERNAL_GRAPH_CONFIGURATION					= 0x8899001F;
	public static final long    D2DERR_CYCLIC_GRAPH											= 0x88990020;
	public static final long    D2DERR_BITMAP_CANNOT_DRAW									= 0x88990021;
	public static final long    D2DERR_OUTSTANDING_BITMAP_REFERENCES						= 0x88990022;
	public static final long    D2DERR_ORIGINAL_TARGET_NOT_BOUND							= 0x88990023;
	public static final long    D2DERR_INVALID_TARGET										= 0x88990024;
	public static final long    D2DERR_BITMAP_BOUND_AS_TARGET								= 0x88990025;
	public static final long    D2DERR_INSUFFICIENT_DEVICE_CAPABILITIES						= 0x88990026;
	public static final long    D2DERR_INTERMEDIATE_TOO_LARGE								= 0x88990027;
	public static final long    D2DERR_EFFECT_IS_NOT_REGISTERED								= 0x88990028;
	public static final long    D2DERR_INVALID_PROPERTY										= 0x88990029;
	public static final long    D2DERR_NO_SUBPROPERTIES										= 0x8899002A;
	public static final long    D2DERR_PRINT_JOB_CLOSED										= 0x8899002B;
	public static final long    D2DERR_PRINT_FORMAT_NOT_SUPPORTED							= 0x8899002C;
	public static final long    D2DERR_TOO_MANY_TRANSFORM_INPUTS							= 0x8899002D;
	public static final long    DWRITE_E_FILEFORMAT											= 0x88985000;
	public static final long    DWRITE_E_UNEXPECTED											= 0x88985001;
	public static final long    DWRITE_E_NOFONT												= 0x88985002;
	public static final long    DWRITE_E_FILENOTFOUND										= 0x88985003;
	public static final long    DWRITE_E_FILEACCESS											= 0x88985004;
	public static final long    DWRITE_E_FONTCOLLECTIONOBSOLETE								= 0x88985005;
	public static final long    DWRITE_E_ALREADYREGISTERED									= 0x88985006;
	public static final long    DWRITE_E_CACHEFORMAT										= 0x88985007;
	public static final long    DWRITE_E_CACHEVERSION										= 0x88985008;
	public static final long    DWRITE_E_UNSUPPORTEDOPERATION								= 0x88985009;
	public static final long    WINCODEC_ERR_WRONGSTATE										= 0x88982F04;
	public static final long    WINCODEC_ERR_VALUEOUTOFRANGE								= 0x88982F05;
	public static final long    WINCODEC_ERR_UNKNOWNIMAGEFORMAT								= 0x88982F07;
	public static final long    WINCODEC_ERR_UNSUPPORTEDVERSION								= 0x88982F0B;
	public static final long    WINCODEC_ERR_NOTINITIALIZED									= 0x88982F0C;
	public static final long    WINCODEC_ERR_ALREADYLOCKED									= 0x88982F0D;
	public static final long    WINCODEC_ERR_PROPERTYNOTFOUND								= 0x88982F40;
	public static final long    WINCODEC_ERR_PROPERTYNOTSUPPORTED							= 0x88982F41;
	public static final long    WINCODEC_ERR_PROPERTYSIZE									= 0x88982F42;
	public static final long    WINCODEC_ERR_CODECPRESENT									= 0x88982F43;
	public static final long    WINCODEC_ERR_CODECNOTHUMBNAIL								= 0x88982F44;
	public static final long    WINCODEC_ERR_PALETTEUNAVAILABLE								= 0x88982F45;
	public static final long    WINCODEC_ERR_CODECTOOMANYSCANLINES							= 0x88982F46;
	public static final long    WINCODEC_ERR_INTERNALERROR									= 0x88982F48;
	public static final long    WINCODEC_ERR_SOURCERECTDOESNOTMATCHDIMENSIONS				= 0x88982F49;
	public static final long    WINCODEC_ERR_COMPONENTNOTFOUND								= 0x88982F50;
	public static final long    WINCODEC_ERR_IMAGESIZEOUTOFRANGE							= 0x88982F51;
	public static final long    WINCODEC_ERR_TOOMUCHMETADATA								= 0x88982F52;
	public static final long    WINCODEC_ERR_BADIMAGE										= 0x88982F60;
	public static final long    WINCODEC_ERR_BADHEADER										= 0x88982F61;
	public static final long    WINCODEC_ERR_FRAMEMISSING									= 0x88982F62;
	public static final long    WINCODEC_ERR_BADMETADATAHEADER								= 0x88982F63;
	public static final long    WINCODEC_ERR_BADSTREAMDATA									= 0x88982F70;
	public static final long    WINCODEC_ERR_STREAMWRITE									= 0x88982F71;
	public static final long    WINCODEC_ERR_STREAMREAD										= 0x88982F72;
	public static final long    WINCODEC_ERR_STREAMNOTAVAILABLE								= 0x88982F73;
	public static final long    WINCODEC_ERR_UNSUPPORTEDPIXELFORMAT							= 0x88982F80;
	public static final long    WINCODEC_ERR_UNSUPPORTEDOPERATION							= 0x88982F81;
	public static final long    WINCODEC_ERR_INVALIDREGISTRATION							= 0x88982F8A;
	public static final long    WINCODEC_ERR_COMPONENTINITIALIZEFAILURE						= 0x88982F8B;
	public static final long    WINCODEC_ERR_INSUFFICIENTBUFFER								= 0x88982F8C;
	public static final long    WINCODEC_ERR_DUPLICATEMETADATAPRESENT						= 0x88982F8D;
	public static final long    WINCODEC_ERR_PROPERTYUNEXPECTEDTYPE							= 0x88982F8E;
	public static final long    WINCODEC_ERR_UNEXPECTEDSIZE									= 0x88982F8F;
	public static final long    WINCODEC_ERR_INVALIDQUERYREQUEST							= 0x88982F90;
	public static final long    WINCODEC_ERR_UNEXPECTEDMETADATATYPE							= 0x88982F91;
	public static final long    WINCODEC_ERR_REQUESTONLYVALIDATMETADATAROOT					= 0x88982F92;
	public static final long    WINCODEC_ERR_INVALIDQUERYCHARACTER							= 0x88982F93;
	public static final long    WINCODEC_ERR_WIN32ERROR										= 0x88982F94;
	public static final long    WINCODEC_ERR_INVALIDPROGRESSIVELEVEL						= 0x88982F95;
	
	private static final Map<Long, String> errorDescription = new HashMap<Long, String>();
	static {
		errorDescription.put(	E_INVALIDARG											,	"There's an invalid argument for the function call.");
		errorDescription.put(   UI_E_CREATE_FAILED										,	"The object could not be created.");
		errorDescription.put(   UI_E_SHUTDOWN_CALLED									,	"Shutdown was already called on this object or the object that owns it.");
		errorDescription.put(   UI_E_ILLEGAL_REENTRANCY									,	"This method cannot be called during this type of callback.");
		errorDescription.put(   UI_E_OBJECT_SEALED										,	"This object has been sealed, so this change is no longer allowed.");
		errorDescription.put(   UI_E_VALUE_NOT_SET										,	"The requested value was never set.");
		errorDescription.put(   UI_E_VALUE_NOT_DETERMINED								,	"The requested value cannot be determined.");
		errorDescription.put(   UI_E_INVALID_OUTPUT										,	"A callback returned an invalid output parameter.");
		errorDescription.put(   UI_E_BOOLEAN_EXPECTED									,	"A callback returned a success code other than S_OK or S_FALSE.");
		errorDescription.put(   UI_E_DIFFERENT_OWNER									,	"A parameter that should be owned by this object is owned by a different object.");
		errorDescription.put(   UI_E_AMBIGUOUS_MATCH									,	"More than one item matched the search criteria.");
		errorDescription.put(   UI_E_FP_OVERFLOW										,	"A floating-point overflow occurred.");
		errorDescription.put(   UI_E_WRONG_THREAD										,	"This method can only be called from the thread that created the object.");
		errorDescription.put(   UI_E_STORYBOARD_ACTIVE									,	"The storyboard is currently in the schedule.");
		errorDescription.put(   UI_E_STORYBOARD_NOT_PLAYING								,	"The storyboard is not playing.");
		errorDescription.put(   UI_E_START_KEYFRAME_AFTER_END							,	"The start keyframe might occur after the end keyframe.");
		errorDescription.put(   UI_E_END_KEYFRAME_NOT_DETERMINED						,	"It might not be possible to determine the end keyframe time when the start keyframe is reached.");
		errorDescription.put(   UI_E_LOOPS_OVERLAP										,	"Two repeated portions of a storyboard might overlap.");
		errorDescription.put(   UI_E_TRANSITION_ALREADY_USED							,	"The transition has already been added to a storyboard.");
		errorDescription.put(   UI_E_TRANSITION_NOT_IN_STORYBOARD						,	"The transition has not been added to a storyboard.");
		errorDescription.put(   UI_E_TRANSITION_ECLIPSED								,	"The transition might eclipse the beginning of another transition in the storyboard.");
		errorDescription.put(   UI_E_TIME_BEFORE_LAST_UPDATE							,	"The given time is earlier than the time passed to the last update.");
		errorDescription.put(   UI_E_TIMER_CLIENT_ALREADY_CONNECTED						,	"This client is already connected to a timer.");
		errorDescription.put(   UI_E_INVALID_DIMENSION									,	"The passed dimension is invalid or does not match the object's dimension.");
		errorDescription.put(   UI_E_PRIMITIVE_OUT_OF_BOUNDS							,	"The added primitive begins at or beyond the duration of the interpolator.");
		errorDescription.put(   UI_E_WINDOW_CLOSED										,	"The operation cannot be completed because the window is being closed.");
		errorDescription.put(   E_AUDIO_ENGINE_NODE_NOT_FOUND							,	"PortCls could not find an audio engine node exposed by a miniport driver claiming support for IMiniportAudioEngineNode.");
		errorDescription.put(   D3DERR_INVALIDCALL                                      ,   "The operation is invalid.");
        errorDescription.put(   DXGI_STATUS_OCCLUDED									,	"The Present operation was invisible to the user.");
		errorDescription.put(   DXGI_STATUS_CLIPPED										,	"The Present operation was partially invisible to the user.");
		errorDescription.put(   DXGI_STATUS_NO_REDIRECTION								,	"The driver is requesting that the DXGI runtime not use shared resources to communicate with the Desktop Window Manager.");
		errorDescription.put(   DXGI_STATUS_NO_DESKTOP_ACCESS							,	"The Present operation was not visible because the Windows session has switched to another desktop (for example, ctrl-alt-del).");
		errorDescription.put(   DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE				,	"The Present operation was not visible because the target monitor was being used for some other purpose.");
		errorDescription.put(   DXGI_STATUS_MODE_CHANGED								,	"The Present operation was not visible because the display mode changed. DXGI will have re-attempted the presentation.");
		errorDescription.put(   DXGI_STATUS_MODE_CHANGE_IN_PROGRESS						,	"The Present operation was not visible because another Direct3D device was attempting to take fullscreen mode at the time.");
		errorDescription.put(   DXGI_ERROR_INVALID_CALL									,	"The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect. Enable the D3D debug layer in order to see details via debug messages.");
		errorDescription.put(   DXGI_ERROR_NOT_FOUND									,	"The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal.");
		errorDescription.put(   DXGI_ERROR_MORE_DATA									,	"The caller did not supply a sufficiently large buffer.");
		errorDescription.put(   DXGI_ERROR_UNSUPPORTED									,	"The specified device interface or feature level is not supported on this system.");
		errorDescription.put(   DXGI_ERROR_DEVICE_REMOVED								,	"The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.");
		errorDescription.put(   DXGI_ERROR_DEVICE_HUNG									,	"The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application.");
		errorDescription.put(   DXGI_ERROR_DEVICE_RESET									,	"The GPU will not respond to more commands, most likely because some other application submitted invalid commands. The calling application should re-create the device and continue.");
		errorDescription.put(   DXGI_ERROR_WAS_STILL_DRAWING							,	"The GPU was busy at the moment when the call was made, and the call was neither executed nor scheduled.");
		errorDescription.put(   DXGI_ERROR_FRAME_STATISTICS_DISJOINT					,	"An event (such as power cycle) interrupted the gathering of presentation statistics. Any previous statistics should be considered invalid.");
		errorDescription.put(   DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE					,	"Fullscreen mode could not be achieved because the specified output was already in use.");
		errorDescription.put(   DXGI_ERROR_DRIVER_INTERNAL_ERROR						,	"An internal issue prevented the driver from carrying out the specified operation. The driver's state is probably suspect, and the application should not continue.");
		errorDescription.put(   DXGI_ERROR_NONEXCLUSIVE									,	"A global counter resource was in use, and the specified counter cannot be used by this Direct3D device at this time.");
		errorDescription.put(   DXGI_ERROR_NOT_CURRENTLY_AVAILABLE						,	"A resource is not available at the time of the call, but may become available later.");
		errorDescription.put(   DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED					,	"The application's remote device has been removed due to session disconnect or network disconnect. The application should call IDXGIFactory1::IsCurrent to find out when the remote device becomes available again.");
		errorDescription.put(   DXGI_ERROR_REMOTE_OUTOFMEMORY							,	"The device has been removed during a remote session because the remote computer ran out of memory.");
		errorDescription.put(   DXGI_ERROR_ACCESS_LOST									,	"The keyed mutex was abandoned.");
		errorDescription.put(   DXGI_ERROR_WAIT_TIMEOUT									,	"The timeout value has elapsed and the resource is not yet available.");
		errorDescription.put(   DXGI_ERROR_SESSION_DISCONNECTED							,	"The output duplication has been turned off because the Windows session ended or was disconnected. This happens when a remote user disconnects, or when \"switch user\" is used locally.");
		errorDescription.put(   DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE						,	"The DXGI outuput (monitor) to which the swapchain content was restricted, has been disconnected or changed.");
		errorDescription.put(   DXGI_ERROR_CANNOT_PROTECT_CONTENT						,	"DXGI is unable to provide content protection on the swapchain. This is typically caused by an older driver, or by the application using a swapchain that is incompatible with content protection.");
		errorDescription.put(   DXGI_ERROR_ACCESS_DENIED								,	"The application is trying to use a resource to which it does not have the required access privileges. This is most commonly caused by writing to a shared resource with read-only access.");
		errorDescription.put(   DXGI_STATUS_UNOCCLUDED									,	"The swapchain has become unoccluded.");
		errorDescription.put(   DXGI_STATUS_DDA_WAS_STILL_DRAWING						,	"The adapter did not have access to the required resources to complete the Desktop Duplication Present() call, the Present() call needs to be made again.");
		errorDescription.put(   DXGI_ERROR_MODE_CHANGE_IN_PROGRESS						,	"An on-going mode change prevented completion of the call. The call may succeed if attempted later.");
		errorDescription.put(   DXGI_DDI_ERR_WASSTILLDRAWING							,	"The GPU was busy when the operation was requested.");
		errorDescription.put(   DXGI_DDI_ERR_UNSUPPORTED								,	"The driver has rejected the creation of this resource.");
		errorDescription.put(   DXGI_DDI_ERR_NONEXCLUSIVE								,	"The GPU counter was in use by another process or d3d device when application requested access to it.");
		errorDescription.put(   D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS				,	"The application has exceeded the maximum number of unique state objects per Direct3D device. The limit is 4096 for feature levels up to 11.1.");
		errorDescription.put(   D3D10_ERROR_FILE_NOT_FOUND								,	"The specified file was not found.");
		errorDescription.put(   D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS				,	"The application has exceeded the maximum number of unique state objects per Direct3D device. The limit is 4096 for feature levels up to 11.1.");
		errorDescription.put(   D3D11_ERROR_FILE_NOT_FOUND								,	"The specified file was not found.");
		errorDescription.put(   D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS				,	"The application has exceeded the maximum number of unique view objects per Direct3D device. The limit is 2^20 for feature levels up to 11.1.");
		errorDescription.put(   D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD,	"The application's first call per command list to Map on a deferred context did not use D3D11_MAP_WRITE_DISCARD.");
		errorDescription.put(   D2DERR_WRONG_STATE										,	"The object was not in the correct state to process the method.");
		errorDescription.put(   D2DERR_NOT_INITIALIZED									,	"The object has not yet been initialized.");
		errorDescription.put(   D2DERR_UNSUPPORTED_OPERATION							,	"The requested operation is not supported.");
		errorDescription.put(   D2DERR_SCANNER_FAILED									,	"The geometry scanner failed to process the data.");
		errorDescription.put(   D2DERR_SCREEN_ACCESS_DENIED								,	"Direct2D could not access the screen.");
		errorDescription.put(   D2DERR_DISPLAY_STATE_INVALID							,	"A valid display state could not be determined.");
		errorDescription.put(   D2DERR_ZERO_VECTOR										,	"The supplied vector is zero.");
		errorDescription.put(   D2DERR_INTERNAL_ERROR									,	"An internal error (Direct2D bug) occurred. On checked builds, we would assert. The application should close this instance of Direct2D and should consider restarting its process.");
		errorDescription.put(   D2DERR_DISPLAY_FORMAT_NOT_SUPPORTED						,	"The display format Direct2D needs to render is not supported by the hardware device.");
		errorDescription.put(   D2DERR_INVALID_CALL										,	"A call to this method is invalid.");
		errorDescription.put(   D2DERR_NO_HARDWARE_DEVICE								,	"No hardware rendering device is available for this operation.");
		errorDescription.put(   D2DERR_RECREATE_TARGET									,	"There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.");
		errorDescription.put(   D2DERR_TOO_MANY_SHADER_ELEMENTS							,	"Shader construction failed because it was too complex.");
		errorDescription.put(   D2DERR_SHADER_COMPILE_FAILED							,	"Shader compilation failed.");
		errorDescription.put(   D2DERR_MAX_TEXTURE_SIZE_EXCEEDED						,	"Requested DirectX surface size exceeded maximum texture size.");
		errorDescription.put(   D2DERR_UNSUPPORTED_VERSION								,	"The requested Direct2D version is not supported.");
		errorDescription.put(   D2DERR_BAD_NUMBER										,	"Invalid number.");
		errorDescription.put(   D2DERR_WRONG_FACTORY									,	"Objects used together must be created from the same factory instance.");
		errorDescription.put(   D2DERR_LAYER_ALREADY_IN_USE								,	"A layer resource can only be in use once at any point in time.");
		errorDescription.put(   D2DERR_POP_CALL_DID_NOT_MATCH_PUSH						,	"The pop call did not match the corresponding push call.");
		errorDescription.put(   D2DERR_WRONG_RESOURCE_DOMAIN							,	"The resource was realized on the wrong render target.");
		errorDescription.put(   D2DERR_PUSH_POP_UNBALANCED								,	"The push and pop calls were unbalanced.");
		errorDescription.put(   D2DERR_RENDER_TARGET_HAS_LAYER_OR_CLIPRECT				,	"Attempt to copy from a render target while a layer or clip rect is applied.");
		errorDescription.put(   D2DERR_INCOMPATIBLE_BRUSH_TYPES							,	"The brush types are incompatible for the call.");
		errorDescription.put(   D2DERR_WIN32_ERROR										,	"An unknown win32 failure occurred.");
		errorDescription.put(   D2DERR_TARGET_NOT_GDI_COMPATIBLE						,	"The render target is not compatible with GDI.");
		errorDescription.put(   D2DERR_TEXT_EFFECT_IS_WRONG_TYPE						,	"A text client drawing effect object is of the wrong type.");
		errorDescription.put(   D2DERR_TEXT_RENDERER_NOT_RELEASED						,	"The application is holding a reference to the IDWriteTextRenderer interface after the corresponding DrawText or DrawTextLayout call has returned. The IDWriteTextRenderer instance will be invalid.");
		errorDescription.put(   D2DERR_EXCEEDS_MAX_BITMAP_SIZE							,	"The requested size is larger than the guaranteed supported texture size at the Direct3D device's current feature level.");
		errorDescription.put(   D2DERR_INVALID_GRAPH_CONFIGURATION						,	"There was a configuration error in the graph.");
		errorDescription.put(   D2DERR_INVALID_INTERNAL_GRAPH_CONFIGURATION				,	"There was a internal configuration error in the graph.");
		errorDescription.put(   D2DERR_CYCLIC_GRAPH										,	"There was a cycle in the graph.");
		errorDescription.put(   D2DERR_BITMAP_CANNOT_DRAW								,	"Cannot draw with a bitmap that has the D2D1_BITMAP_OPTIONS_CANNOT_DRAW option.");
		errorDescription.put(   D2DERR_OUTSTANDING_BITMAP_REFERENCES					,	"The operation cannot complete while there are outstanding references to the target bitmap.");
		errorDescription.put(   D2DERR_ORIGINAL_TARGET_NOT_BOUND						,	"The operation failed because the original target is not currently bound as a target.");
		errorDescription.put(   D2DERR_INVALID_TARGET									,	"Cannot set the image as a target because it is either an effect or is a bitmap that does not have the D2D1_BITMAP_OPTIONS_TARGET flag set.");
		errorDescription.put(   D2DERR_BITMAP_BOUND_AS_TARGET							,	"Cannot draw with a bitmap that is currently bound as the target bitmap.");
		errorDescription.put(   D2DERR_INSUFFICIENT_DEVICE_CAPABILITIES					,	"D3D Device does not have sufficient capabilities to perform the requested action.");
		errorDescription.put(   D2DERR_INTERMEDIATE_TOO_LARGE							,	"The graph could not be rendered with the context's current tiling settings.");
		errorDescription.put(   D2DERR_EFFECT_IS_NOT_REGISTERED							,	"The CLSID provided to Unregister did not correspond to a registered effect.");
		errorDescription.put(   D2DERR_INVALID_PROPERTY									,	"The specified property does not exist.");
		errorDescription.put(   D2DERR_NO_SUBPROPERTIES									,	"The specified sub-property does not exist.");
		errorDescription.put(   D2DERR_PRINT_JOB_CLOSED									,	"AddPage or Close called after print job is already closed.");
		errorDescription.put(   D2DERR_PRINT_FORMAT_NOT_SUPPORTED						,	"Error during print control creation. Indicates that none of the package target types (representing printer formats) are supported by Direct2D print control.");
		errorDescription.put(   D2DERR_TOO_MANY_TRANSFORM_INPUTS						,	"An effect attempted to use a transform with too many inputs.");
		errorDescription.put(   DWRITE_E_FILEFORMAT										,	"Indicates an error in an input file such as a font file.");
		errorDescription.put(   DWRITE_E_UNEXPECTED										,	"Indicates an error originating in DirectWrite code, which is not expected to occur but is safe to recover from.");
		errorDescription.put(   DWRITE_E_NOFONT											,	"Indicates the specified font does not exist.");
		errorDescription.put(   DWRITE_E_FILENOTFOUND									,	"A font file could not be opened because the file, directory, network location, drive, or other storage location does not exist or is unavailable.");
		errorDescription.put(   DWRITE_E_FILEACCESS										,	"A font file exists but could not be opened due to access denied, sharing violation, or similar error.");
		errorDescription.put(   DWRITE_E_FONTCOLLECTIONOBSOLETE							,	"A font collection is obsolete due to changes in the system.");
		errorDescription.put(   DWRITE_E_ALREADYREGISTERED								,	"The given interface is already registered.");
		errorDescription.put(   DWRITE_E_CACHEFORMAT									,	"The font cache contains invalid data.");
		errorDescription.put(   DWRITE_E_CACHEVERSION									,	"A font cache file corresponds to a different version of DirectWrite.");
		errorDescription.put(   DWRITE_E_UNSUPPORTEDOPERATION							,	"The operation is not supported for this type of font.");
		errorDescription.put(   WINCODEC_ERR_WRONGSTATE									,	"The codec is in the wrong state.");
		errorDescription.put(   WINCODEC_ERR_VALUEOUTOFRANGE							,	"The value is out of range.");
		errorDescription.put(   WINCODEC_ERR_UNKNOWNIMAGEFORMAT							,	"The image format is unknown.");
		errorDescription.put(   WINCODEC_ERR_UNSUPPORTEDVERSION							,	"The SDK version is unsupported.");
		errorDescription.put(   WINCODEC_ERR_NOTINITIALIZED								,	"The component is not initialized.");
		errorDescription.put(   WINCODEC_ERR_ALREADYLOCKED								,	"There is already an outstanding read or write lock.");
		errorDescription.put(   WINCODEC_ERR_PROPERTYNOTFOUND							,	"The specified bitmap property cannot be found.");
		errorDescription.put(   WINCODEC_ERR_PROPERTYNOTSUPPORTED						,	"The bitmap codec does not support the bitmap property.");
		errorDescription.put(   WINCODEC_ERR_PROPERTYSIZE								,	"The bitmap property size is invalid.");
		errorDescription.put(   WINCODEC_ERR_CODECPRESENT								,	"An unknown error has occurred.");
		errorDescription.put(   WINCODEC_ERR_CODECNOTHUMBNAIL							,	"The bitmap codec does not support a thumbnail.");
		errorDescription.put(   WINCODEC_ERR_PALETTEUNAVAILABLE							,	"The bitmap palette is unavailable.");
		errorDescription.put(   WINCODEC_ERR_CODECTOOMANYSCANLINES						,	"Too many scanlines were requested.");
		errorDescription.put(   WINCODEC_ERR_INTERNALERROR								,	"An internal error occurred.");
		errorDescription.put(   WINCODEC_ERR_SOURCERECTDOESNOTMATCHDIMENSIONS			,	"The bitmap bounds do not match the bitmap dimensions.");
		errorDescription.put(   WINCODEC_ERR_COMPONENTNOTFOUND							,	"The component cannot be found.");
		errorDescription.put(   WINCODEC_ERR_IMAGESIZEOUTOFRANGE						,	"The bitmap size is outside the valid range.");
		errorDescription.put(   WINCODEC_ERR_TOOMUCHMETADATA							,	"There is too much metadata to be written to the bitmap.");
		errorDescription.put(   WINCODEC_ERR_BADIMAGE									,	"The image is unrecognized.");
		errorDescription.put(   WINCODEC_ERR_BADHEADER									,	"The image header is unrecognized.");
		errorDescription.put(   WINCODEC_ERR_FRAMEMISSING								,	"The bitmap frame is missing.");
		errorDescription.put(   WINCODEC_ERR_BADMETADATAHEADER							,	"The image metadata header is unrecognized.");
		errorDescription.put(   WINCODEC_ERR_BADSTREAMDATA								,	"The stream data is unrecognized.");
		errorDescription.put(   WINCODEC_ERR_STREAMWRITE								,	"Failed to write to the stream.");
		errorDescription.put(   WINCODEC_ERR_STREAMREAD									,	"Failed to read from the stream.");
		errorDescription.put(   WINCODEC_ERR_STREAMNOTAVAILABLE							,	"The stream is not available.");
		errorDescription.put(   WINCODEC_ERR_UNSUPPORTEDPIXELFORMAT						,	"The bitmap pixel format is unsupported.");
		errorDescription.put(   WINCODEC_ERR_UNSUPPORTEDOPERATION						,	"The operation is unsupported.");
		errorDescription.put(   WINCODEC_ERR_INVALIDREGISTRATION						,	"The component registration is invalid.");
		errorDescription.put(   WINCODEC_ERR_COMPONENTINITIALIZEFAILURE					,	"The component initialization has failed.");
		errorDescription.put(   WINCODEC_ERR_INSUFFICIENTBUFFER							,	"The buffer allocated is insufficient.");
		errorDescription.put(   WINCODEC_ERR_DUPLICATEMETADATAPRESENT					,	"Duplicate metadata is present.");
		errorDescription.put(   WINCODEC_ERR_PROPERTYUNEXPECTEDTYPE						,	"The bitmap property type is unexpected.");
		errorDescription.put(   WINCODEC_ERR_UNEXPECTEDSIZE								,	"The size is unexpected.");
		errorDescription.put(   WINCODEC_ERR_INVALIDQUERYREQUEST						,	"The property query is invalid.");
		errorDescription.put(   WINCODEC_ERR_UNEXPECTEDMETADATATYPE						,	"The metadata type is unexpected.");
		errorDescription.put(   WINCODEC_ERR_REQUESTONLYVALIDATMETADATAROOT				,	"The specified bitmap property is only valid at root level.");
		errorDescription.put(   WINCODEC_ERR_INVALIDQUERYCHARACTER						,	"The query string contains an invalid character.");
		errorDescription.put(   WINCODEC_ERR_WIN32ERROR									,	"Windows Codecs received an error from the Win32 system.");
		errorDescription.put(   WINCODEC_ERR_INVALIDPROGRESSIVELEVEL					,	"The requested level of detail is not present.");
	}
	
	private final long errorCode;
	private final String detailMessage;
	
	public WindowsException(long errorCode) {
		super(errorDescription.get(errorCode));
		
		this.errorCode = errorCode;
		this.detailMessage = errorDescription.get(errorCode);
	}
	
	public WindowsException(String message, long errorCode) {
		super(errorDescription.get(errorCode));
		
		this.errorCode = errorCode;
		this.detailMessage = message;
	}

	public long getCode() {
		return errorCode;
	}
	
	public String getErrorDescription() {
		return errorDescription.get(errorCode);
	}
	
	public String getDetailMessage() {
		return detailMessage;
	}
}
