package com.fourthskyinteractive.dx4j.d3d11.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d11") 
public class D3D11_VIEWPORT extends StructObject {
	public D3D11_VIEWPORT() {
		super();
	}
	public D3D11_VIEWPORT(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	public D3D11_VIEWPORT(float width, float height) {
		super();
		this.Width(width).Height(height).TopLeftX(0.0f).TopLeftY(0.0f).MinDepth(0.0f).MaxDepth(1.0f);
	}
	@Field(0) 
	public float TopLeftX() {
		return this.io.getFloatField(this, 0);
	}
	@Field(0) 
	public D3D11_VIEWPORT TopLeftX(float TopLeftX) {
		this.io.setFloatField(this, 0, TopLeftX);
		return this;
	}
	@Field(1) 
	public float TopLeftY() {
		return this.io.getFloatField(this, 1);
	}
	@Field(1) 
	public D3D11_VIEWPORT TopLeftY(float TopLeftY) {
		this.io.setFloatField(this, 1, TopLeftY);
		return this;
	}
	@Field(2) 
	public float Width() {
		return this.io.getFloatField(this, 2);
	}
	@Field(2) 
	public D3D11_VIEWPORT Width(float Width) {
		this.io.setFloatField(this, 2, Width);
		return this;
	}
	@Field(3) 
	public float Height() {
		return this.io.getFloatField(this, 3);
	}
	@Field(3) 
	public D3D11_VIEWPORT Height(float Height) {
		this.io.setFloatField(this, 3, Height);
		return this;
	}
	@Field(4) 
	public float MinDepth() {
		return this.io.getFloatField(this, 4);
	}
	@Field(4) 
	public D3D11_VIEWPORT MinDepth(float MinDepth) {
		this.io.setFloatField(this, 4, MinDepth);
		return this;
	}
	@Field(5) 
	public float MaxDepth() {
		return this.io.getFloatField(this, 5);
	}
	@Field(5) 
	public D3D11_VIEWPORT MaxDepth(float MaxDepth) {
		this.io.setFloatField(this, 5, MaxDepth);
		return this;
	}
}
