package com.fourthskyinteractive.dx4j.d3d9.states;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DVERTEXELEMENT9 extends StructObject {
	public D3DVERTEXELEMENT9() {
		super();
	}
	public D3DVERTEXELEMENT9(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public short Stream() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public D3DVERTEXELEMENT9 Stream(short Stream) {
		this.io.setShortField(this, 0, Stream);
		return this;
	}
	@Field(1) 
	public short Offset() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public D3DVERTEXELEMENT9 Offset(short Offset) {
		this.io.setShortField(this, 1, Offset);
		return this;
	}
	@Field(2) 
	public byte Type() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public D3DVERTEXELEMENT9 Type(byte Type) {
		this.io.setByteField(this, 2, Type);
		return this;
	}
	@Field(3) 
	public byte Method() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public D3DVERTEXELEMENT9 Method(byte Method) {
		this.io.setByteField(this, 3, Method);
		return this;
	}
	@Field(4) 
	public byte Usage() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public D3DVERTEXELEMENT9 Usage(byte Usage) {
		this.io.setByteField(this, 4, Usage);
		return this;
	}
	@Field(5) 
	public byte UsageIndex() {
		return this.io.getByteField(this, 5);
	}
	@Field(5) 
	public D3DVERTEXELEMENT9 UsageIndex(byte UsageIndex) {
		this.io.setByteField(this, 5, UsageIndex);
		return this;
	}
}
