package com.fourthskyinteractive.dx4j.d2d1.resources.brush;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d2d1.resources.geometry.D2D1_POINT_2F;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d2d1") 
public class D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES extends StructObject {
	public D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES() {
		super();
	}
	public D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : D2D1_POINT_2F
	@Field(0) 
	public D2D1_POINT_2F center() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : D2D1_POINT_2F
	@Field(1) 
	public D2D1_POINT_2F gradientOriginOffset() {
		return this.io.getNativeObjectField(this, 1);
	}
	@Field(2) 
	public float radiusX() {
		return this.io.getFloatField(this, 2);
	}
	@Field(2) 
	public D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES radiusX(float radiusX) {
		this.io.setFloatField(this, 2, radiusX);
		return this;
	}
	@Field(3) 
	public float radiusY() {
		return this.io.getFloatField(this, 3);
	}
	@Field(3) 
	public D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES radiusY(float radiusY) {
		this.io.setFloatField(this, 3, radiusY);
		return this;
	}
}
