package com.fourthskyinteractive.dx4j.d3d9.resources;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DLOCKED_BOX extends StructObject {
	public D3DLOCKED_BOX() {
		super();
	}
	public D3DLOCKED_BOX(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public int RowPitch() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public D3DLOCKED_BOX RowPitch(int RowPitch) {
		this.io.setIntField(this, 0, RowPitch);
		return this;
	}
	@Field(1) 
	public int SlicePitch() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public D3DLOCKED_BOX SlicePitch(int SlicePitch) {
		this.io.setIntField(this, 1, SlicePitch);
		return this;
	}
	/// C type : void*
	@Field(2) 
	public Pointer<? > pBits() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : void*
	@Field(2) 
	public D3DLOCKED_BOX pBits(Pointer<? > pBits) {
		this.io.setPointerField(this, 2, pBits);
		return this;
	}
}
