package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CameraInfo_t extends Structure {
	public int width;
	public int height;
	public int depth;
	public float fx;
	public float cx;
	public float fy;
	public float cy;
	public CameraInfo_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("width", "height", "depth", "fx", "cx", "fy", "cy");
	}
	public CameraInfo_t(int width, int height, int depth, float fx, float cx, float fy, float cy) {
		super();
		this.width = width;
		this.height = height;
		this.depth = depth;
		this.fx = fx;
		this.cx = cx;
		this.fy = fy;
		this.cy = cy;
	}
	public CameraInfo_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CameraInfo_t implements Structure.ByReference {
		
	};
	public static class ByValue extends CameraInfo_t implements Structure.ByValue {
		
	};
}
