package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/phr00t/OpenVR/headers/openvr_capi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ChaperoneSeatedBoundsInfo_t extends Structure {
	/** C type : HmdVector3_t */
	public HmdVector3_t vSeatedHeadPosition;
	/**
	 * HmdVector3_t[2]<br>
	 * C type : HmdVector3_t[2]
	 */
	public HmdVector3_t[] vDeskEdgePositions = new HmdVector3_t[2];
	public ChaperoneSeatedBoundsInfo_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("vSeatedHeadPosition", "vDeskEdgePositions");
	}
	/**
	 * @param vSeatedHeadPosition C type : HmdVector3_t<br>
	 * @param vDeskEdgePositions HmdVector3_t[2]<br>
	 * C type : HmdVector3_t[2]
	 */
	public ChaperoneSeatedBoundsInfo_t(HmdVector3_t vSeatedHeadPosition, HmdVector3_t vDeskEdgePositions[]) {
		super();
		this.vSeatedHeadPosition = vSeatedHeadPosition;
		if ((vDeskEdgePositions.length != this.vDeskEdgePositions.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.vDeskEdgePositions = vDeskEdgePositions;
	}
	public ChaperoneSeatedBoundsInfo_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ChaperoneSeatedBoundsInfo_t implements Structure.ByReference {
		
	};
	public static class ByValue extends ChaperoneSeatedBoundsInfo_t implements Structure.ByValue {
		
	};
}
