package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ComponentState_t extends Structure {
	/** C type : HmdMatrix34_t */
	public HmdMatrix34_t mTrackingToComponentRenderModel;
	/** C type : HmdMatrix34_t */
	public HmdMatrix34_t mTrackingToComponentLocal;
	public byte bIsStatic;
	public byte bIsVisible;
	public ComponentState_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("mTrackingToComponentRenderModel", "mTrackingToComponentLocal", "bIsStatic", "bIsVisible");
	}
	/**
	 * @param mTrackingToComponentRenderModel C type : HmdMatrix34_t<br>
	 * @param mTrackingToComponentLocal C type : HmdMatrix34_t
	 */
	public ComponentState_t(HmdMatrix34_t mTrackingToComponentRenderModel, HmdMatrix34_t mTrackingToComponentLocal, byte bIsStatic, byte bIsVisible) {
		super();
		this.mTrackingToComponentRenderModel = mTrackingToComponentRenderModel;
		this.mTrackingToComponentLocal = mTrackingToComponentLocal;
		this.bIsStatic = bIsStatic;
		this.bIsVisible = bIsVisible;
	}
	public ComponentState_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ComponentState_t implements Structure.ByReference {
		
	};
	public static class ByValue extends ComponentState_t implements Structure.ByValue {
		
	};
}
