package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/phr00t/OpenVR/headers/openvr_capi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotificationBitmap extends Structure {
	/**
	 * char *<br>
	 * C type : char*
	 */
	public Pointer bytes;
	public int width;
	public int height;
	public int depth;
	public NotificationBitmap() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("bytes", "width", "height", "depth");
	}
	/**
	 * @param bytes char *<br>
	 * C type : char*
	 */
	public NotificationBitmap(Pointer bytes, int width, int height, int depth) {
		super();
		this.bytes = bytes;
		this.width = width;
		this.height = height;
		this.depth = depth;
	}
	public NotificationBitmap(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NotificationBitmap implements Structure.ByReference {
		
	};
	public static class ByValue extends NotificationBitmap implements Structure.ByValue {
		
	};
}
