package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : headers\openvr_capi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotificationItem extends Structure {
	public int notificationId;
	public NotificationItem() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("notificationId");
	}
	public NotificationItem(int notificationId) {
		super();
		this.notificationId = notificationId;
	}
	public NotificationItem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NotificationItem implements Structure.ByReference {
		
	};
	public static class ByValue extends NotificationItem implements Structure.ByValue {
		
	};
}
