package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TrackedCameraCalibrationDevOnly_t extends Structure {
	public double m_flIntrinsicsFX;
	public double m_flIntrinsicsFY;
	public double m_flIntrinsicsCX;
	public double m_flIntrinsicsCY;
	public double m_flIntrinsicsK1;
	public double m_flIntrinsicsK2;
	public double m_flIntrinsicsP1;
	public double m_flIntrinsicsP2;
	public double m_flIntrinsicsK3;
	public TrackedCameraCalibrationDevOnly_t() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("m_flIntrinsicsFX", "m_flIntrinsicsFY", "m_flIntrinsicsCX", "m_flIntrinsicsCY", "m_flIntrinsicsK1", "m_flIntrinsicsK2", "m_flIntrinsicsP1", "m_flIntrinsicsP2", "m_flIntrinsicsK3");
	}
	public TrackedCameraCalibrationDevOnly_t(double m_flIntrinsicsFX, double m_flIntrinsicsFY, double m_flIntrinsicsCX, double m_flIntrinsicsCY, double m_flIntrinsicsK1, double m_flIntrinsicsK2, double m_flIntrinsicsP1, double m_flIntrinsicsP2, double m_flIntrinsicsK3) {
		super();
		this.m_flIntrinsicsFX = m_flIntrinsicsFX;
		this.m_flIntrinsicsFY = m_flIntrinsicsFY;
		this.m_flIntrinsicsCX = m_flIntrinsicsCX;
		this.m_flIntrinsicsCY = m_flIntrinsicsCY;
		this.m_flIntrinsicsK1 = m_flIntrinsicsK1;
		this.m_flIntrinsicsK2 = m_flIntrinsicsK2;
		this.m_flIntrinsicsP1 = m_flIntrinsicsP1;
		this.m_flIntrinsicsP2 = m_flIntrinsicsP2;
		this.m_flIntrinsicsK3 = m_flIntrinsicsK3;
	}
	public TrackedCameraCalibrationDevOnly_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TrackedCameraCalibrationDevOnly_t implements Structure.ByReference {
		
	};
	public static class ByValue extends TrackedCameraCalibrationDevOnly_t implements Structure.ByValue {
		
	};
}
