package com.fourthskyinteractive.dx4j.d3d11.states;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;

import com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D11_COMPARISON_FUNC;
import com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D11_STENCIL_OP;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
public class D3D11_DEPTH_STENCILOP_DESC extends StructObject {
	public D3D11_DEPTH_STENCILOP_DESC() {
		super();
	}
	public D3D11_DEPTH_STENCILOP_DESC(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : D3D11_STENCIL_OP
	@Field(0) 
	public ValuedEnum<D3D11_STENCIL_OP > StencilFailOp() {
		return this.io.getEnumField(this, 0);
	}
	/// C type : D3D11_STENCIL_OP
	@Field(0) 
	public D3D11_DEPTH_STENCILOP_DESC StencilFailOp(ValuedEnum<D3D11_STENCIL_OP > StencilFailOp) {
		this.io.setEnumField(this, 0, StencilFailOp);
		return this;
	}
	/// C type : D3D11_STENCIL_OP
	@Field(1) 
	public ValuedEnum<D3D11_STENCIL_OP > StencilDepthFailOp() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : D3D11_STENCIL_OP
	@Field(1) 
	public D3D11_DEPTH_STENCILOP_DESC StencilDepthFailOp(ValuedEnum<D3D11_STENCIL_OP > StencilDepthFailOp) {
		this.io.setEnumField(this, 1, StencilDepthFailOp);
		return this;
	}
	/// C type : D3D11_STENCIL_OP
	@Field(2) 
	public ValuedEnum<D3D11_STENCIL_OP > StencilPassOp() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : D3D11_STENCIL_OP
	@Field(2) 
	public D3D11_DEPTH_STENCILOP_DESC StencilPassOp(ValuedEnum<D3D11_STENCIL_OP > StencilPassOp) {
		this.io.setEnumField(this, 2, StencilPassOp);
		return this;
	}
	/// C type : D3D11_COMPARISON_FUNC
	@Field(3) 
	public ValuedEnum<D3D11_COMPARISON_FUNC > StencilFunc() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : D3D11_COMPARISON_FUNC
	@Field(3) 
	public D3D11_DEPTH_STENCILOP_DESC StencilFunc(ValuedEnum<D3D11_COMPARISON_FUNC > StencilFunc) {
		this.io.setEnumField(this, 3, StencilFunc);
		return this;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int)StencilFailOp().value(); 
		result = prime * result + (int)StencilDepthFailOp().value(); 
		result = prime * result + (int)StencilPassOp().value();
		result = prime * result + (int)StencilFunc().value();
		
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		if(hashCode() != obj.hashCode()) 
			return false;
		
		return true;
	}
}
