package com.fourthskyinteractive.dx4j.d3d11.query;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d11") 
public class D3D11_QUERY_DATA_SO_STATISTICS extends StructObject {
	public D3D11_QUERY_DATA_SO_STATISTICS() {
		super();
	}
	public D3D11_QUERY_DATA_SO_STATISTICS(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : UINT64
	@Field(0) 
	public long NumPrimitivesWritten() {
		return this.io.getLongField(this, 0);
	}
	/// C type : UINT64
	@Field(0) 
	public D3D11_QUERY_DATA_SO_STATISTICS NumPrimitivesWritten(long NumPrimitivesWritten) {
		this.io.setLongField(this, 0, NumPrimitivesWritten);
		return this;
	}
	/// C type : UINT64
	@Field(1) 
	public long PrimitivesStorageNeeded() {
		return this.io.getLongField(this, 1);
	}
	/// C type : UINT64
	@Field(1) 
	public D3D11_QUERY_DATA_SO_STATISTICS PrimitivesStorageNeeded(long PrimitivesStorageNeeded) {
		this.io.setLongField(this, 1, PrimitivesStorageNeeded);
		return this;
	}
}
