package com.fourthskyinteractive.dx4j.d3d11.query;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D11_QUERY;
import com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D11_QUERY_MISC_FLAG;
import com.fourthskyinteractive.dx4j.d3d11.D3D11Exception;

import static com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D11_QUERY.*;

import static com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D11_ASYNC_GETDATA_FLAG;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d11") 
public class D3D11_QUERY_DESC extends StructObject {
	public D3D11_QUERY_DESC() {
		super();
	}
	public D3D11_QUERY_DESC(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : D3D11_QUERY
	@Field(0) 
	public ValuedEnum<D3D11_QUERY > Query() {
		return this.io.getEnumField(this, 0);
	}
	/// C type : D3D11_QUERY
	@Field(0) 
	public D3D11_QUERY_DESC Query(ValuedEnum<D3D11_QUERY > Query) {
		this.io.setEnumField(this, 0, Query);
		return this;
	}

    @Field(1)
    public ValuedEnum<D3D11_QUERY_MISC_FLAG> MiscFlags() {
        return this.io.getEnumField(this, 1);
    }
    @Field(1)
    public D3D11_QUERY_DESC MiscFlags(ValuedEnum<D3D11_QUERY_MISC_FLAG> MiscFlags) {
        this.io.setEnumField(this, 1, MiscFlags);
        return this;
    }

    /**
     * Utility method that informs the return class of query
     * @return
     */
    public Class<?> ResultClass() {
    	/*
        D3D11_QUERY queryType = (D3D11_QUERY) Query();
        switch(queryType) {
            case D3D11_QUERY_OCCLUSION:
                return Long.class;
            case D3D11_QUERY_TIMESTAMP:
                return Long.class;
            case D3D11_QUERY_TIMESTAMP_DISJOINT:
                return D3D11_QUERY_DATA_TIMESTAMP_DISJOINT.class;
            case D3D11_QUERY_PIPELINE_STATISTICS:
                return D3D11_QUERY_DATA_PIPELINE_STATISTICS.class;
            case D3D11_QUERY_SO_STATISTICS:
            case D3D11_QUERY_SO_STATISTICS_STREAM0:
            case D3D11_QUERY_SO_STATISTICS_STREAM1:
            case D3D11_QUERY_SO_STATISTICS_STREAM2:
            case D3D11_QUERY_SO_STATISTICS_STREAM3:
                return D3D11_QUERY_DATA_SO_STATISTICS.class;
            case D3D11_QUERY_EVENT:
            case D3D11_QUERY_OCCLUSION_PREDICATE:
            case D3D11_QUERY_SO_OVERFLOW_PREDICATE:
            case D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM0:
            case D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM1:
            case D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM2:
            case D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM3:
            default:
                return Integer.class;
        }
        */
    	
    	ValuedEnum<D3D11_QUERY> query = Query();
    	if (D3D11_QUERY_OCCLUSION == query ||
    		D3D11_QUERY_TIMESTAMP == query)
    		return Long.class;
    	
    	else if (D3D11_QUERY_TIMESTAMP_DISJOINT == query)
    		return D3D11_QUERY_DATA_TIMESTAMP_DISJOINT.class;
    	
    	else if (D3D11_QUERY_PIPELINE_STATISTICS == query)
    		return D3D11_QUERY_DATA_PIPELINE_STATISTICS.class;
    	
    	else if (D3D11_QUERY_SO_STATISTICS == query 		||
    			 D3D11_QUERY_SO_STATISTICS_STREAM0 == query ||
    			 D3D11_QUERY_SO_STATISTICS_STREAM1 == query ||
    			 D3D11_QUERY_SO_STATISTICS_STREAM2 == query ||
    			 D3D11_QUERY_SO_STATISTICS_STREAM3 == query)
    		return D3D11_QUERY_DATA_SO_STATISTICS.class;
    	/*
    	else if (D3D11_QUERY_EVENT == query 						||
    			 D3D11_QUERY_SO_OVERFLOW_PREDICATE == query 		||
    			 D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM0 == query	||
    			 D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM1 == query	||
    			 D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM2 == query	||
    			 D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM3 == query)
    		return Integer.class;
    	*/
    	return Integer.class;
    }
}
