package com.fourthskyinteractive.dx4j.d3d9;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DMATRIX extends StructObject {
	public D3DMATRIX() {
		super();
	}
	public D3DMATRIX(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : DUMMYUNIONNAME_union
	@Field(0) 
	public D3DMATRIX.DUMMYUNIONNAME_union DUMMYUNIONNAME() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// <i>native declaration : line 1402</i>
	@Union 
	public static class DUMMYUNIONNAME_union extends StructObject {
		public DUMMYUNIONNAME_union() {
			super();
		}
		public DUMMYUNIONNAME_union(Pointer<? extends StructObject> pointer) {
			super(pointer);
		}
		/// C type : DUMMYSTRUCTNAME_struct
		@Field(0) 
		public D3DMATRIX.DUMMYUNIONNAME_union.DUMMYSTRUCTNAME_struct DUMMYSTRUCTNAME() {
			return this.io.getNativeObjectField(this, 0);
		}
		/// C type : float[4][4]
		@Array({4, 4}) 
		@Field(1) 
		public Pointer<Float > m() {
			return this.io.getPointerField(this, 1);
		}
		/// <i>native declaration : line 1403</i>
		public static class DUMMYSTRUCTNAME_struct extends StructObject {
			public DUMMYSTRUCTNAME_struct() {
				super();
			}
			public DUMMYSTRUCTNAME_struct(Pointer<? extends StructObject> pointer) {
				super(pointer);
			}
			@Field(0) 
			public float _11() {
				return this.io.getFloatField(this, 0);
			}
			@Field(0) 
			public DUMMYSTRUCTNAME_struct _11(float _11) {
				this.io.setFloatField(this, 0, _11);
				return this;
			}
			@Field(1) 
			public float _12() {
				return this.io.getFloatField(this, 1);
			}
			@Field(1) 
			public DUMMYSTRUCTNAME_struct _12(float _12) {
				this.io.setFloatField(this, 1, _12);
				return this;
			}
			@Field(2) 
			public float _13() {
				return this.io.getFloatField(this, 2);
			}
			@Field(2) 
			public DUMMYSTRUCTNAME_struct _13(float _13) {
				this.io.setFloatField(this, 2, _13);
				return this;
			}
			@Field(3) 
			public float _14() {
				return this.io.getFloatField(this, 3);
			}
			@Field(3) 
			public DUMMYSTRUCTNAME_struct _14(float _14) {
				this.io.setFloatField(this, 3, _14);
				return this;
			}
			@Field(4) 
			public float _21() {
				return this.io.getFloatField(this, 4);
			}
			@Field(4) 
			public DUMMYSTRUCTNAME_struct _21(float _21) {
				this.io.setFloatField(this, 4, _21);
				return this;
			}
			@Field(5) 
			public float _22() {
				return this.io.getFloatField(this, 5);
			}
			@Field(5) 
			public DUMMYSTRUCTNAME_struct _22(float _22) {
				this.io.setFloatField(this, 5, _22);
				return this;
			}
			@Field(6) 
			public float _23() {
				return this.io.getFloatField(this, 6);
			}
			@Field(6) 
			public DUMMYSTRUCTNAME_struct _23(float _23) {
				this.io.setFloatField(this, 6, _23);
				return this;
			}
			@Field(7) 
			public float _24() {
				return this.io.getFloatField(this, 7);
			}
			@Field(7) 
			public DUMMYSTRUCTNAME_struct _24(float _24) {
				this.io.setFloatField(this, 7, _24);
				return this;
			}
			@Field(8) 
			public float _31() {
				return this.io.getFloatField(this, 8);
			}
			@Field(8) 
			public DUMMYSTRUCTNAME_struct _31(float _31) {
				this.io.setFloatField(this, 8, _31);
				return this;
			}
			@Field(9) 
			public float _32() {
				return this.io.getFloatField(this, 9);
			}
			@Field(9) 
			public DUMMYSTRUCTNAME_struct _32(float _32) {
				this.io.setFloatField(this, 9, _32);
				return this;
			}
			@Field(10) 
			public float _33() {
				return this.io.getFloatField(this, 10);
			}
			@Field(10) 
			public DUMMYSTRUCTNAME_struct _33(float _33) {
				this.io.setFloatField(this, 10, _33);
				return this;
			}
			@Field(11) 
			public float _34() {
				return this.io.getFloatField(this, 11);
			}
			@Field(11) 
			public DUMMYSTRUCTNAME_struct _34(float _34) {
				this.io.setFloatField(this, 11, _34);
				return this;
			}
			@Field(12) 
			public float _41() {
				return this.io.getFloatField(this, 12);
			}
			@Field(12) 
			public DUMMYSTRUCTNAME_struct _41(float _41) {
				this.io.setFloatField(this, 12, _41);
				return this;
			}
			@Field(13) 
			public float _42() {
				return this.io.getFloatField(this, 13);
			}
			@Field(13) 
			public DUMMYSTRUCTNAME_struct _42(float _42) {
				this.io.setFloatField(this, 13, _42);
				return this;
			}
			@Field(14) 
			public float _43() {
				return this.io.getFloatField(this, 14);
			}
			@Field(14) 
			public DUMMYSTRUCTNAME_struct _43(float _43) {
				this.io.setFloatField(this, 14, _43);
				return this;
			}
			@Field(15) 
			public float _44() {
				return this.io.getFloatField(this, 15);
			}
			@Field(15) 
			public DUMMYSTRUCTNAME_struct _44(float _44) {
				this.io.setFloatField(this, 15, _44);
				return this;
			}
		};
	};
}
