package com.fourthskyinteractive.dx4j.d3d9;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DRECT extends StructObject {
	public D3DRECT() {
		super();
	}
	public D3DRECT(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@CLong 
	@Field(0) 
	public long x1() {
		return this.io.getCLongField(this, 0);
	}
	@CLong 
	@Field(0) 
	public D3DRECT x1(long x1) {
		this.io.setCLongField(this, 0, x1);
		return this;
	}
	@CLong 
	@Field(1) 
	public long y1() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public D3DRECT y1(long y1) {
		this.io.setCLongField(this, 1, y1);
		return this;
	}
	@CLong 
	@Field(2) 
	public long x2() {
		return this.io.getCLongField(this, 2);
	}
	@CLong 
	@Field(2) 
	public D3DRECT x2(long x2) {
		this.io.setCLongField(this, 2, x2);
		return this;
	}
	@CLong 
	@Field(3) 
	public long y2() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public D3DRECT y2(long y2) {
		this.io.setCLongField(this, 3, y2);
		return this;
	}
}
