package com.fourthskyinteractive.dx4j.dxgi;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

@Library("dxgi") 
public class DXGI_RATIONAL extends StructObject {
	public DXGI_RATIONAL() {
		super();
	}
	public DXGI_RATIONAL(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public int Numerator() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public DXGI_RATIONAL Numerator(int Numerator) {
		this.io.setIntField(this, 0, Numerator);
		return this;
	}
	@Field(1) 
	public int Denominator() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public DXGI_RATIONAL Denominator(int Denominator) {
		this.io.setIntField(this, 1, Denominator);
		return this;
	}
}
