package osvrrendermanageropengl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public /*abstract*/ class OSVR_RenderInfoOpenGL extends Structure {
	/** C type : OSVR_GraphicsLibraryOpenGL */
	public OSVR_GraphicsLibraryOpenGL library;
	/** C type : OSVR_ViewportDescription */
	public OSVR_ViewportDescription viewport;
	/**
	 * Conversion Error : struct OSVR_Pose3 {<br>
	 * 	struct OSVR_Vec3 {<br>
	 * 		double[3] data;<br>
	 * 	} translation;<br>
	 * 	struct OSVR_Quaternion {<br>
	 * 		double[4] data;<br>
	 * 	} rotation;<br>
	 * }
	 */
	/** C type : OSVR_ProjectionMatrix */
	public OSVR_ProjectionMatrix projection;
	public OSVR_RenderInfoOpenGL() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("library", "viewport", "projection");
	}
	/**
	 * @param library C type : OSVR_GraphicsLibraryOpenGL<br>
	 * @param viewport C type : OSVR_ViewportDescription<br>
	 * @param projection C type : OSVR_ProjectionMatrix
	 */
	public OSVR_RenderInfoOpenGL(OSVR_GraphicsLibraryOpenGL library, OSVR_ViewportDescription viewport, OSVR_ProjectionMatrix projection) {
		super();
		this.library = library;
		this.viewport = viewport;
		this.projection = projection;
	}
	public OSVR_RenderInfoOpenGL(Pointer peer) {
		super(peer);
	}
	public static /*abstract*/ class ByReference extends OSVR_RenderInfoOpenGL implements Structure.ByReference {
		
	};
	public static /*abstract*/ class ByValue extends OSVR_RenderInfoOpenGL implements Structure.ByValue {
		
	};
}
