package com.fourthskyinteractive.dx4j.d3d9.query;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DDEVINFO_VCACHE extends StructObject {
	public D3DDEVINFO_VCACHE() {
		super();
	}
	public D3DDEVINFO_VCACHE(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// Must be a 4 char code FOURCC (e.g. CACH)
	@Field(0) 
	public int Pattern() {
		return this.io.getIntField(this, 0);
	}
	/// Must be a 4 char code FOURCC (e.g. CACH)
	@Field(0) 
	public D3DDEVINFO_VCACHE Pattern(int Pattern) {
		this.io.setIntField(this, 0, Pattern);
		return this;
	}
	/// 0 to get the longest  strips, 1 vertex cache
	@Field(1) 
	public int OptMethod() {
		return this.io.getIntField(this, 1);
	}
	/// 0 to get the longest  strips, 1 vertex cache
	@Field(1) 
	public D3DDEVINFO_VCACHE OptMethod(int OptMethod) {
		this.io.setIntField(this, 1, OptMethod);
		return this;
	}
	/// Cache size to use (only valid if OptMethod==1)
	@Field(2) 
	public int CacheSize() {
		return this.io.getIntField(this, 2);
	}
	/// Cache size to use (only valid if OptMethod==1)
	@Field(2) 
	public D3DDEVINFO_VCACHE CacheSize(int CacheSize) {
		this.io.setIntField(this, 2, CacheSize);
		return this;
	}
	/// internal for deciding when to restart strips, non user modifiable (only valid if OptMethod==1)
	@Field(3) 
	public int MagicNumber() {
		return this.io.getIntField(this, 3);
	}
	/// internal for deciding when to restart strips, non user modifiable (only valid if OptMethod==1)
	@Field(3) 
	public D3DDEVINFO_VCACHE MagicNumber(int MagicNumber) {
		this.io.setIntField(this, 3, MagicNumber);
		return this;
	}
}
