package com.fourthskyinteractive.dx4j.d3d9.query;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DDEVINFO_D3D9PIPELINETIMINGS extends StructObject {
	public D3DDEVINFO_D3D9PIPELINETIMINGS() {
		super();
	}
	public D3DDEVINFO_D3D9PIPELINETIMINGS(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public float VertexProcessingTimePercent() {
		return this.io.getFloatField(this, 0);
	}
	@Field(0) 
	public D3DDEVINFO_D3D9PIPELINETIMINGS VertexProcessingTimePercent(float VertexProcessingTimePercent) {
		this.io.setFloatField(this, 0, VertexProcessingTimePercent);
		return this;
	}
	@Field(1) 
	public float PixelProcessingTimePercent() {
		return this.io.getFloatField(this, 1);
	}
	@Field(1) 
	public D3DDEVINFO_D3D9PIPELINETIMINGS PixelProcessingTimePercent(float PixelProcessingTimePercent) {
		this.io.setFloatField(this, 1, PixelProcessingTimePercent);
		return this;
	}
	@Field(2) 
	public float OtherGPUProcessingTimePercent() {
		return this.io.getFloatField(this, 2);
	}
	@Field(2) 
	public D3DDEVINFO_D3D9PIPELINETIMINGS OtherGPUProcessingTimePercent(float OtherGPUProcessingTimePercent) {
		this.io.setFloatField(this, 2, OtherGPUProcessingTimePercent);
		return this;
	}
	@Field(3) 
	public float GPUIdleTimePercent() {
		return this.io.getFloatField(this, 3);
	}
	@Field(3) 
	public D3DDEVINFO_D3D9PIPELINETIMINGS GPUIdleTimePercent(float GPUIdleTimePercent) {
		this.io.setFloatField(this, 3, GPUIdleTimePercent);
		return this;
	}
}
