package com.fourthskyinteractive.dx4j.d3d9.query;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d9.resources.D3DRESOURCESTATS;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DDEVINFO_D3DRESOURCEMANAGER extends StructObject {
	public D3DDEVINFO_D3DRESOURCEMANAGER() {
		super();
	}
	public D3DDEVINFO_D3DRESOURCEMANAGER(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : D3DRESOURCESTATS[(D3DRTYPE_INDEXBUFFER + 1)]
	//@Array({D3DRTYPE_INDEXBUFFER.value + 1}) 
	@Array({8})
	@Field(0) 
	public Pointer<D3DRESOURCESTATS > stats() {
		return this.io.getPointerField(this, 0);
	}
}
