package com.fourthskyinteractive.dx4j.dxgi.adapter;

import com.fourthskyinteractive.dx4j.windows.kernel32.LARGE_INTEGER;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("DXGI")
public class DXGI_OUTDUPL_FRAME_INFO extends StructObject {
    /** C type : LARGE_INTEGER */
    @Field(0)
    public LARGE_INTEGER LastPresentTime() {
        return this.io.getNativeObjectField(this, 0);
    }
    /** C type : LARGE_INTEGER */
    @Field(0)
    public DXGI_OUTDUPL_FRAME_INFO LastPresentTime(LARGE_INTEGER LastPresentTime) {
        this.io.setNativeObjectField(this, 0, LastPresentTime);
        return this;
    }
    /** C type : LARGE_INTEGER */
    @Field(1)
    public LARGE_INTEGER LastMouseUpdateTime() {
        return this.io.getNativeObjectField(this, 1);
    }
    /** C type : LARGE_INTEGER */
    @Field(1)
    public DXGI_OUTDUPL_FRAME_INFO LastMouseUpdateTime(LARGE_INTEGER LastMouseUpdateTime) {
        this.io.setNativeObjectField(this, 1, LastMouseUpdateTime);
        return this;
    }
    @Field(2)
    public int AccumulatedFrames() {
        return this.io.getIntField(this, 2);
    }
    @Field(2)
    public DXGI_OUTDUPL_FRAME_INFO AccumulatedFrames(int AccumulatedFrames) {
        this.io.setIntField(this, 2, AccumulatedFrames);
        return this;
    }
    @Field(3)
    public int RectsCoalesced() {
        return this.io.getIntField(this, 3);
    }
    @Field(3)
    public DXGI_OUTDUPL_FRAME_INFO RectsCoalesced(int RectsCoalesced) {
        this.io.setIntField(this, 3, RectsCoalesced);
        return this;
    }
    @Field(4)
    public int ProtectedContentMaskedOut() {
        return this.io.getIntField(this, 4);
    }
    @Field(4)
    public DXGI_OUTDUPL_FRAME_INFO ProtectedContentMaskedOut(int ProtectedContentMaskedOut) {
        this.io.setIntField(this, 4, ProtectedContentMaskedOut);
        return this;
    }
    /** C type : DXGI_OUTDUPL_POINTER_POSITION */
    @Field(5)
    public DXGI_OUTDUPL_POINTER_POSITION PointerPosition() {
        return this.io.getNativeObjectField(this, 5);
    }
    /** C type : DXGI_OUTDUPL_POINTER_POSITION */
    @Field(5)
    public DXGI_OUTDUPL_FRAME_INFO PointerPosition(DXGI_OUTDUPL_POINTER_POSITION PointerPosition) {
        this.io.setNativeObjectField(this, 5, PointerPosition);
        return this;
    }
    @Field(6)
    public int TotalMetadataBufferSize() {
        return this.io.getIntField(this, 6);
    }
    @Field(6)
    public DXGI_OUTDUPL_FRAME_INFO TotalMetadataBufferSize(int TotalMetadataBufferSize) {
        this.io.setIntField(this, 6, TotalMetadataBufferSize);
        return this;
    }
    @Field(7)
    public int PointerShapeBufferSize() {
        return this.io.getIntField(this, 7);
    }
    @Field(7)
    public DXGI_OUTDUPL_FRAME_INFO PointerShapeBufferSize(int PointerShapeBufferSize) {
        this.io.setIntField(this, 7, PointerShapeBufferSize);
        return this;
    }
    public DXGI_OUTDUPL_FRAME_INFO() {
        super();
    }
    @SuppressWarnings({ "rawtypes", "unchecked" })
	public DXGI_OUTDUPL_FRAME_INFO(Pointer pointer) {
        super(pointer);
    }
}
