package com.fourthskyinteractive.dx4j.dxgi.adapter;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : DXGI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dxgi") 
public class DXGI_FRAME_STATISTICS extends StructObject {
	public DXGI_FRAME_STATISTICS() {
		super();
	}
	public DXGI_FRAME_STATISTICS(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public int PresentCount() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public DXGI_FRAME_STATISTICS PresentCount(int PresentCount) {
		this.io.setIntField(this, 0, PresentCount);
		return this;
	}
	@Field(1) 
	public int PresentRefreshCount() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public DXGI_FRAME_STATISTICS PresentRefreshCount(int PresentRefreshCount) {
		this.io.setIntField(this, 1, PresentRefreshCount);
		return this;
	}
	@Field(2) 
	public int SyncRefreshCount() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public DXGI_FRAME_STATISTICS SyncRefreshCount(int SyncRefreshCount) {
		this.io.setIntField(this, 2, SyncRefreshCount);
		return this;
	}
}
