package com.fourthskyinteractive.dx4j.dxgi.adapter;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.windows.LUID;
/**
 * <i>native declaration : DXGI.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("dxgi") 
public class DXGI_ADAPTER_DESC extends StructObject {
	public DXGI_ADAPTER_DESC() {
		super();
	}
	public DXGI_ADAPTER_DESC(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : WCHAR[128]
	@Array({128}) 
	@Field(0) 
	public Pointer<Short > Description() {
		return this.io.getPointerField(this, 0);
	}
	@Field(1) 
	public int VendorId() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public DXGI_ADAPTER_DESC VendorId(int VendorId) {
		this.io.setIntField(this, 1, VendorId);
		return this;
	}
	@Field(2) 
	public int DeviceId() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public DXGI_ADAPTER_DESC DeviceId(int DeviceId) {
		this.io.setIntField(this, 2, DeviceId);
		return this;
	}
	@Field(3) 
	public int SubSysId() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public DXGI_ADAPTER_DESC SubSysId(int SubSysId) {
		this.io.setIntField(this, 3, SubSysId);
		return this;
	}
	@Field(4) 
	public int Revision() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public DXGI_ADAPTER_DESC Revision(int Revision) {
		this.io.setIntField(this, 4, Revision);
		return this;
	}
	@CLong 
	@Field(5) 
	public long DedicatedVideoMemory() {
		return this.io.getCLongField(this, 5);
	}
	@CLong 
	@Field(5) 
	public DXGI_ADAPTER_DESC DedicatedVideoMemory(long DedicatedVideoMemory) {
		this.io.setCLongField(this, 5, DedicatedVideoMemory);
		return this;
	}
	@CLong 
	@Field(6) 
	public long DedicatedSystemMemory() {
		return this.io.getCLongField(this, 6);
	}
	@CLong 
	@Field(6) 
	public DXGI_ADAPTER_DESC DedicatedSystemMemory(long DedicatedSystemMemory) {
		this.io.setCLongField(this, 6, DedicatedSystemMemory);
		return this;
	}
	@CLong 
	@Field(7) 
	public long SharedSystemMemory() {
		return this.io.getCLongField(this, 7);
	}
	@CLong 
	@Field(7) 
	public DXGI_ADAPTER_DESC SharedSystemMemory(long SharedSystemMemory) {
		this.io.setCLongField(this, 7, SharedSystemMemory);
		return this;
	}
	
	@Field(8)
	public LUID AdapterLuid() {
		return this.io.getNativeObjectField(this, 8);
	}
	@Field(8)
	public DXGI_ADAPTER_DESC SharedSystemMemory(LUID AdapterLuid) {
		this.io.setNativeObjectField(this, 8, AdapterLuid);
		return this;
	}
}
