package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.windows.kernel32.LARGE_INTEGER;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DADAPTER_IDENTIFIER9 extends StructObject {
	public D3DADAPTER_IDENTIFIER9() {
		super();
	}
	public D3DADAPTER_IDENTIFIER9(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : char[512]
	@Array({512}) 
	@Field(0) 
	public Pointer<Byte > Driver() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char[512]
	@Array({512}) 
	@Field(1) 
	public Pointer<Byte > Description() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : char[32]
	@Array({32}) 
	@Field(2) 
	public Pointer<Byte > DeviceName() {
		return this.io.getPointerField(this, 2);
	}
	
	@Field(3)
	public LARGE_INTEGER DriverVersion() {
		return this.io.getNativeObjectField(this, 3);
	}
	
	@Field(4) 
	public int DriverVersionLowPart() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public D3DADAPTER_IDENTIFIER9 DriverVersionLowPart(int DriverVersionLowPart) {
		this.io.setIntField(this, 4, DriverVersionLowPart);
		return this;
	}
	
	@Field(5) 
	public int DriverVersionHighPart() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public D3DADAPTER_IDENTIFIER9 DriverVersionHighPart(int DriverVersionHighPart) {
		this.io.setIntField(this, 5, DriverVersionHighPart);
		return this;
	}
	
	@Field(6) 
	public int VendorId() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public D3DADAPTER_IDENTIFIER9 VendorId(int VendorId) {
		this.io.setIntField(this, 6, VendorId);
		return this;
	}
	@Field(7) 
	public int DeviceId() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public D3DADAPTER_IDENTIFIER9 DeviceId(int DeviceId) {
		this.io.setIntField(this, 7, DeviceId);
		return this;
	}
	@Field(8) 
	public int SubSysId() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public D3DADAPTER_IDENTIFIER9 SubSysId(int SubSysId) {
		this.io.setIntField(this, 8, SubSysId);
		return this;
	}
	@Field(9) 
	public int Revision() {
		return this.io.getIntField(this, 97);
	}
	@Field(9) 
	public D3DADAPTER_IDENTIFIER9 Revision(int Revision) {
		this.io.setIntField(this, 9, Revision);
		return this;
	}
	
	@Field(10)
	public Pointer<Byte> DeviceIdentifier() {
		return this.io.getPointerField(this, 10);
	}
	@Field(10)
	public D3DADAPTER_IDENTIFIER9 DeviceIdentifier(Pointer<Byte> DeviceIdentifier) {
		this.io.setPointerField(this, 10, DeviceIdentifier);
		return this;
	}
	
	@Field(11) 
	public int WHQLLevel() {
		return this.io.getIntField(this, 11);
	}
	@Field(11) 
	public D3DADAPTER_IDENTIFIER9 WHQLLevel(int WHQLLevel) {
		this.io.setIntField(this, 11, WHQLLevel);
		return this;
	}
}
