package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d9.shader.D3DPSHADERCAPS2_0;
import com.fourthskyinteractive.dx4j.d3d9.shader.D3DVSHADERCAPS2_0;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("D3D9") 
public class D3DCAPS9 extends StructObject {
	public D3DCAPS9() {
		super();
	}
	public D3DCAPS9(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(1) 
	public int AdapterOrdinal() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public D3DCAPS9 AdapterOrdinal(int AdapterOrdinal) {
		this.io.setIntField(this, 1, AdapterOrdinal);
		return this;
	}
	@Field(2) 
	public int Caps() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public D3DCAPS9 Caps(int Caps) {
		this.io.setIntField(this, 2, Caps);
		return this;
	}
	@Field(3) 
	public int Caps2() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public D3DCAPS9 Caps2(int Caps2) {
		this.io.setIntField(this, 3, Caps2);
		return this;
	}
	@Field(4) 
	public int Caps3() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public D3DCAPS9 Caps3(int Caps3) {
		this.io.setIntField(this, 4, Caps3);
		return this;
	}
	@Field(5) 
	public int PresentationIntervals() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public D3DCAPS9 PresentationIntervals(int PresentationIntervals) {
		this.io.setIntField(this, 5, PresentationIntervals);
		return this;
	}
	@Field(6) 
	public int CursorCaps() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public D3DCAPS9 CursorCaps(int CursorCaps) {
		this.io.setIntField(this, 6, CursorCaps);
		return this;
	}
	@Field(7) 
	public int DevCaps() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public D3DCAPS9 DevCaps(int DevCaps) {
		this.io.setIntField(this, 7, DevCaps);
		return this;
	}
	@Field(8) 
	public int PrimitiveMiscCaps() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public D3DCAPS9 PrimitiveMiscCaps(int PrimitiveMiscCaps) {
		this.io.setIntField(this, 8, PrimitiveMiscCaps);
		return this;
	}
	@Field(9) 
	public int RasterCaps() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public D3DCAPS9 RasterCaps(int RasterCaps) {
		this.io.setIntField(this, 9, RasterCaps);
		return this;
	}
	@Field(10) 
	public int ZCmpCaps() {
		return this.io.getIntField(this, 10);
	}
	@Field(10) 
	public D3DCAPS9 ZCmpCaps(int ZCmpCaps) {
		this.io.setIntField(this, 10, ZCmpCaps);
		return this;
	}
	@Field(11) 
	public int SrcBlendCaps() {
		return this.io.getIntField(this, 11);
	}
	@Field(11) 
	public D3DCAPS9 SrcBlendCaps(int SrcBlendCaps) {
		this.io.setIntField(this, 11, SrcBlendCaps);
		return this;
	}
	@Field(12) 
	public int DestBlendCaps() {
		return this.io.getIntField(this, 12);
	}
	@Field(12) 
	public D3DCAPS9 DestBlendCaps(int DestBlendCaps) {
		this.io.setIntField(this, 12, DestBlendCaps);
		return this;
	}
	@Field(13) 
	public int AlphaCmpCaps() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public D3DCAPS9 AlphaCmpCaps(int AlphaCmpCaps) {
		this.io.setIntField(this, 13, AlphaCmpCaps);
		return this;
	}
	@Field(14) 
	public int ShadeCaps() {
		return this.io.getIntField(this, 14);
	}
	@Field(14) 
	public D3DCAPS9 ShadeCaps(int ShadeCaps) {
		this.io.setIntField(this, 14, ShadeCaps);
		return this;
	}
	@Field(15) 
	public int TextureCaps() {
		return this.io.getIntField(this, 15);
	}
	@Field(15) 
	public D3DCAPS9 TextureCaps(int TextureCaps) {
		this.io.setIntField(this, 15, TextureCaps);
		return this;
	}
	@Field(16) 
	public int TextureFilterCaps() {
		return this.io.getIntField(this, 16);
	}
	@Field(16) 
	public D3DCAPS9 TextureFilterCaps(int TextureFilterCaps) {
		this.io.setIntField(this, 16, TextureFilterCaps);
		return this;
	}
	@Field(17) 
	public int CubeTextureFilterCaps() {
		return this.io.getIntField(this, 17);
	}
	@Field(17) 
	public D3DCAPS9 CubeTextureFilterCaps(int CubeTextureFilterCaps) {
		this.io.setIntField(this, 17, CubeTextureFilterCaps);
		return this;
	}
	@Field(18) 
	public int VolumeTextureFilterCaps() {
		return this.io.getIntField(this, 18);
	}
	@Field(18) 
	public D3DCAPS9 VolumeTextureFilterCaps(int VolumeTextureFilterCaps) {
		this.io.setIntField(this, 18, VolumeTextureFilterCaps);
		return this;
	}
	@Field(19) 
	public int TextureAddressCaps() {
		return this.io.getIntField(this, 19);
	}
	@Field(19) 
	public D3DCAPS9 TextureAddressCaps(int TextureAddressCaps) {
		this.io.setIntField(this, 19, TextureAddressCaps);
		return this;
	}
	@Field(20) 
	public int VolumeTextureAddressCaps() {
		return this.io.getIntField(this, 20);
	}
	@Field(20) 
	public D3DCAPS9 VolumeTextureAddressCaps(int VolumeTextureAddressCaps) {
		this.io.setIntField(this, 20, VolumeTextureAddressCaps);
		return this;
	}
	@Field(21) 
	public int LineCaps() {
		return this.io.getIntField(this, 21);
	}
	@Field(21) 
	public D3DCAPS9 LineCaps(int LineCaps) {
		this.io.setIntField(this, 21, LineCaps);
		return this;
	}
	@Field(22) 
	public int MaxTextureWidth() {
		return this.io.getIntField(this, 22);
	}
	@Field(22) 
	public D3DCAPS9 MaxTextureWidth(int MaxTextureWidth) {
		this.io.setIntField(this, 22, MaxTextureWidth);
		return this;
	}
	@Field(23) 
	public int MaxTextureHeight() {
		return this.io.getIntField(this, 23);
	}
	@Field(23) 
	public D3DCAPS9 MaxTextureHeight(int MaxTextureHeight) {
		this.io.setIntField(this, 23, MaxTextureHeight);
		return this;
	}
	@Field(24) 
	public int MaxVolumeExtent() {
		return this.io.getIntField(this, 24);
	}
	@Field(24) 
	public D3DCAPS9 MaxVolumeExtent(int MaxVolumeExtent) {
		this.io.setIntField(this, 24, MaxVolumeExtent);
		return this;
	}
	@Field(25) 
	public int MaxTextureRepeat() {
		return this.io.getIntField(this, 25);
	}
	@Field(25) 
	public D3DCAPS9 MaxTextureRepeat(int MaxTextureRepeat) {
		this.io.setIntField(this, 25, MaxTextureRepeat);
		return this;
	}
	@Field(26) 
	public int MaxTextureAspectRatio() {
		return this.io.getIntField(this, 26);
	}
	@Field(26) 
	public D3DCAPS9 MaxTextureAspectRatio(int MaxTextureAspectRatio) {
		this.io.setIntField(this, 26, MaxTextureAspectRatio);
		return this;
	}
	@Field(27) 
	public int MaxAnisotropy() {
		return this.io.getIntField(this, 27);
	}
	@Field(27) 
	public D3DCAPS9 MaxAnisotropy(int MaxAnisotropy) {
		this.io.setIntField(this, 27, MaxAnisotropy);
		return this;
	}
	@Field(28) 
	public float MaxVertexW() {
		return this.io.getFloatField(this, 28);
	}
	@Field(28) 
	public D3DCAPS9 MaxVertexW(float MaxVertexW) {
		this.io.setFloatField(this, 28, MaxVertexW);
		return this;
	}
	@Field(29) 
	public float GuardBandLeft() {
		return this.io.getFloatField(this, 29);
	}
	@Field(29) 
	public D3DCAPS9 GuardBandLeft(float GuardBandLeft) {
		this.io.setFloatField(this, 29, GuardBandLeft);
		return this;
	}
	@Field(30) 
	public float GuardBandTop() {
		return this.io.getFloatField(this, 30);
	}
	@Field(30) 
	public D3DCAPS9 GuardBandTop(float GuardBandTop) {
		this.io.setFloatField(this, 30, GuardBandTop);
		return this;
	}
	@Field(31) 
	public float GuardBandRight() {
		return this.io.getFloatField(this, 31);
	}
	@Field(31) 
	public D3DCAPS9 GuardBandRight(float GuardBandRight) {
		this.io.setFloatField(this, 31, GuardBandRight);
		return this;
	}
	@Field(32) 
	public float GuardBandBottom() {
		return this.io.getFloatField(this, 32);
	}
	@Field(32) 
	public D3DCAPS9 GuardBandBottom(float GuardBandBottom) {
		this.io.setFloatField(this, 32, GuardBandBottom);
		return this;
	}
	@Field(33) 
	public float ExtentsAdjust() {
		return this.io.getFloatField(this, 33);
	}
	@Field(33) 
	public D3DCAPS9 ExtentsAdjust(float ExtentsAdjust) {
		this.io.setFloatField(this, 33, ExtentsAdjust);
		return this;
	}
	@Field(34) 
	public int StencilCaps() {
		return this.io.getIntField(this, 34);
	}
	@Field(34) 
	public D3DCAPS9 StencilCaps(int StencilCaps) {
		this.io.setIntField(this, 34, StencilCaps);
		return this;
	}
	@Field(35) 
	public int FVFCaps() {
		return this.io.getIntField(this, 35);
	}
	@Field(35) 
	public D3DCAPS9 FVFCaps(int FVFCaps) {
		this.io.setIntField(this, 35, FVFCaps);
		return this;
	}
	@Field(36) 
	public int TextureOpCaps() {
		return this.io.getIntField(this, 36);
	}
	@Field(36) 
	public D3DCAPS9 TextureOpCaps(int TextureOpCaps) {
		this.io.setIntField(this, 36, TextureOpCaps);
		return this;
	}
	@Field(37) 
	public int MaxTextureBlendStages() {
		return this.io.getIntField(this, 37);
	}
	@Field(37) 
	public D3DCAPS9 MaxTextureBlendStages(int MaxTextureBlendStages) {
		this.io.setIntField(this, 37, MaxTextureBlendStages);
		return this;
	}
	@Field(38) 
	public int MaxSimultaneousTextures() {
		return this.io.getIntField(this, 38);
	}
	@Field(38) 
	public D3DCAPS9 MaxSimultaneousTextures(int MaxSimultaneousTextures) {
		this.io.setIntField(this, 38, MaxSimultaneousTextures);
		return this;
	}
	@Field(39) 
	public int VertexProcessingCaps() {
		return this.io.getIntField(this, 39);
	}
	@Field(39) 
	public D3DCAPS9 VertexProcessingCaps(int VertexProcessingCaps) {
		this.io.setIntField(this, 39, VertexProcessingCaps);
		return this;
	}
	@Field(40) 
	public int MaxActiveLights() {
		return this.io.getIntField(this, 40);
	}
	@Field(40) 
	public D3DCAPS9 MaxActiveLights(int MaxActiveLights) {
		this.io.setIntField(this, 40, MaxActiveLights);
		return this;
	}
	@Field(41) 
	public int MaxUserClipPlanes() {
		return this.io.getIntField(this, 41);
	}
	@Field(41) 
	public D3DCAPS9 MaxUserClipPlanes(int MaxUserClipPlanes) {
		this.io.setIntField(this, 41, MaxUserClipPlanes);
		return this;
	}
	@Field(42) 
	public int MaxVertexBlendMatrices() {
		return this.io.getIntField(this, 42);
	}
	@Field(42) 
	public D3DCAPS9 MaxVertexBlendMatrices(int MaxVertexBlendMatrices) {
		this.io.setIntField(this, 42, MaxVertexBlendMatrices);
		return this;
	}
	@Field(43) 
	public int MaxVertexBlendMatrixIndex() {
		return this.io.getIntField(this, 43);
	}
	@Field(43) 
	public D3DCAPS9 MaxVertexBlendMatrixIndex(int MaxVertexBlendMatrixIndex) {
		this.io.setIntField(this, 43, MaxVertexBlendMatrixIndex);
		return this;
	}
	@Field(44) 
	public float MaxPointSize() {
		return this.io.getFloatField(this, 44);
	}
	@Field(44) 
	public D3DCAPS9 MaxPointSize(float MaxPointSize) {
		this.io.setFloatField(this, 44, MaxPointSize);
		return this;
	}
	@Field(45) 
	public int MaxPrimitiveCount() {
		return this.io.getIntField(this, 45);
	}
	@Field(45) 
	public D3DCAPS9 MaxPrimitiveCount(int MaxPrimitiveCount) {
		this.io.setIntField(this, 45, MaxPrimitiveCount);
		return this;
	}
	@Field(46) 
	public int MaxVertexIndex() {
		return this.io.getIntField(this, 46);
	}
	@Field(46) 
	public D3DCAPS9 MaxVertexIndex(int MaxVertexIndex) {
		this.io.setIntField(this, 46, MaxVertexIndex);
		return this;
	}
	@Field(47) 
	public int MaxStreams() {
		return this.io.getIntField(this, 47);
	}
	@Field(47) 
	public D3DCAPS9 MaxStreams(int MaxStreams) {
		this.io.setIntField(this, 47, MaxStreams);
		return this;
	}
	@Field(48) 
	public int MaxStreamStride() {
		return this.io.getIntField(this, 48);
	}
	@Field(48) 
	public D3DCAPS9 MaxStreamStride(int MaxStreamStride) {
		this.io.setIntField(this, 48, MaxStreamStride);
		return this;
	}
	@Field(49) 
	public int VertexShaderVersion() {
		return this.io.getIntField(this, 49);
	}
	@Field(49) 
	public D3DCAPS9 VertexShaderVersion(int VertexShaderVersion) {
		this.io.setIntField(this, 49, VertexShaderVersion);
		return this;
	}
	@Field(50) 
	public int MaxVertexShaderConst() {
		return this.io.getIntField(this, 50);
	}
	@Field(50) 
	public D3DCAPS9 MaxVertexShaderConst(int MaxVertexShaderConst) {
		this.io.setIntField(this, 50, MaxVertexShaderConst);
		return this;
	}
	@Field(51) 
	public int PixelShaderVersion() {
		return this.io.getIntField(this, 51);
	}
	@Field(51) 
	public D3DCAPS9 PixelShaderVersion(int PixelShaderVersion) {
		this.io.setIntField(this, 51, PixelShaderVersion);
		return this;
	}
	@Field(52) 
	public float PixelShader1xMaxValue() {
		return this.io.getFloatField(this, 52);
	}
	@Field(52) 
	public D3DCAPS9 PixelShader1xMaxValue(float PixelShader1xMaxValue) {
		this.io.setFloatField(this, 52, PixelShader1xMaxValue);
		return this;
	}
	/// DX 9
	@Field(53) 
	public int DevCaps2() {
		return this.io.getIntField(this, 53);
	}
	/// DX 9
	@Field(53) 
	public D3DCAPS9 DevCaps2(int DevCaps2) {
		this.io.setIntField(this, 53, DevCaps2);
		return this;
	}
	@Field(54) 
	public float MaxNpatchTessellationLevel() {
		return this.io.getFloatField(this, 54);
	}
	@Field(54) 
	public D3DCAPS9 MaxNpatchTessellationLevel(float MaxNpatchTessellationLevel) {
		this.io.setFloatField(this, 54, MaxNpatchTessellationLevel);
		return this;
	}
	@Field(55) 
	public int Reserved5() {
		return this.io.getIntField(this, 55);
	}
	@Field(55) 
	public D3DCAPS9 Reserved5(int Reserved5) {
		this.io.setIntField(this, 55, Reserved5);
		return this;
	}
	@Field(56) 
	public int MasterAdapterOrdinal() {
		return this.io.getIntField(this, 56);
	}
	@Field(56) 
	public D3DCAPS9 MasterAdapterOrdinal(int MasterAdapterOrdinal) {
		this.io.setIntField(this, 56, MasterAdapterOrdinal);
		return this;
	}
	@Field(57) 
	public int AdapterOrdinalInGroup() {
		return this.io.getIntField(this, 57);
	}
	@Field(57) 
	public D3DCAPS9 AdapterOrdinalInGroup(int AdapterOrdinalInGroup) {
		this.io.setIntField(this, 57, AdapterOrdinalInGroup);
		return this;
	}
	@Field(58) 
	public int NumberOfAdaptersInGroup() {
		return this.io.getIntField(this, 58);
	}
	@Field(58) 
	public D3DCAPS9 NumberOfAdaptersInGroup(int NumberOfAdaptersInGroup) {
		this.io.setIntField(this, 58, NumberOfAdaptersInGroup);
		return this;
	}
	@Field(59) 
	public int DeclTypes() {
		return this.io.getIntField(this, 59);
	}
	@Field(59) 
	public D3DCAPS9 DeclTypes(int DeclTypes) {
		this.io.setIntField(this, 59, DeclTypes);
		return this;
	}
	@Field(60) 
	public int NumSimultaneousRTs() {
		return this.io.getIntField(this, 60);
	}
	@Field(60) 
	public D3DCAPS9 NumSimultaneousRTs(int NumSimultaneousRTs) {
		this.io.setIntField(this, 60, NumSimultaneousRTs);
		return this;
	}
	@Field(61) 
	public int StretchRectFilterCaps() {
		return this.io.getIntField(this, 61);
	}
	@Field(61) 
	public D3DCAPS9 StretchRectFilterCaps(int StretchRectFilterCaps) {
		this.io.setIntField(this, 61, StretchRectFilterCaps);
		return this;
	}
	/// C type : D3DVSHADERCAPS2_0
	@Field(62) 
	public D3DVSHADERCAPS2_0 VS20Caps() {
		return this.io.getNativeObjectField(this, 62);
	}
	/// C type : D3DPSHADERCAPS2_0
	@Field(63) 
	public D3DPSHADERCAPS2_0 PS20Caps() {
		return this.io.getNativeObjectField(this, 63);
	}
	@Field(64) 
	public int VertexTextureFilterCaps() {
		return this.io.getIntField(this, 64);
	}
	@Field(64) 
	public D3DCAPS9 VertexTextureFilterCaps(int VertexTextureFilterCaps) {
		this.io.setIntField(this, 64, VertexTextureFilterCaps);
		return this;
	}
	@Field(65) 
	public int MaxVShaderInstructionsExecuted() {
		return this.io.getIntField(this, 65);
	}
	@Field(65) 
	public D3DCAPS9 MaxVShaderInstructionsExecuted(int MaxVShaderInstructionsExecuted) {
		this.io.setIntField(this, 65, MaxVShaderInstructionsExecuted);
		return this;
	}
	@Field(66) 
	public int MaxPShaderInstructionsExecuted() {
		return this.io.getIntField(this, 66);
	}
	@Field(66) 
	public D3DCAPS9 MaxPShaderInstructionsExecuted(int MaxPShaderInstructionsExecuted) {
		this.io.setIntField(this, 66, MaxPShaderInstructionsExecuted);
		return this;
	}
	@Field(67) 
	public int MaxVertexShader30InstructionSlots() {
		return this.io.getIntField(this, 67);
	}
	@Field(67) 
	public D3DCAPS9 MaxVertexShader30InstructionSlots(int MaxVertexShader30InstructionSlots) {
		this.io.setIntField(this, 67, MaxVertexShader30InstructionSlots);
		return this;
	}
	@Field(68) 
	public int MaxPixelShader30InstructionSlots() {
		return this.io.getIntField(this, 68);
	}
	@Field(68) 
	public D3DCAPS9 MaxPixelShader30InstructionSlots(int MaxPixelShader30InstructionSlots) {
		this.io.setIntField(this, 68, MaxPixelShader30InstructionSlots);
		return this;
	}
}
