package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d9.D3D9.D3DFORMAT;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DDISPLAYMODE extends StructObject {
	public D3DDISPLAYMODE() {
		super();
	}
	public D3DDISPLAYMODE(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public int Width() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public D3DDISPLAYMODE Width(int Width) {
		this.io.setIntField(this, 0, Width);
		return this;
	}
	@Field(1) 
	public int Height() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public D3DDISPLAYMODE Height(int Height) {
		this.io.setIntField(this, 1, Height);
		return this;
	}
	@Field(2) 
	public int RefreshRate() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public D3DDISPLAYMODE RefreshRate(int RefreshRate) {
		this.io.setIntField(this, 2, RefreshRate);
		return this;
	}
	/// C type : D3DFORMAT
	@Field(3) 
	public ValuedEnum<D3DFORMAT > Format() {
		return this.io.getEnumField(this, 3);
	}
	/// C type : D3DFORMAT
	@Field(3) 
	public D3DDISPLAYMODE Format(ValuedEnum<D3DFORMAT > Format) {
		this.io.setEnumField(this, 3, Format);
		return this;
	}
}
