package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d9.D3D9.D3DFORMAT;
import com.fourthskyinteractive.dx4j.d3d9.D3D9.D3DSCANLINEORDERING;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DDISPLAYMODEFILTER extends StructObject {
	public D3DDISPLAYMODEFILTER() {
		super();
	}
	public D3DDISPLAYMODEFILTER(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public int Size() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public D3DDISPLAYMODEFILTER Size(int Size) {
		this.io.setIntField(this, 0, Size);
		return this;
	}
	/// C type : D3DFORMAT
	@Field(1) 
	public ValuedEnum<D3DFORMAT > Format() {
		return this.io.getEnumField(this, 1);
	}
	/// C type : D3DFORMAT
	@Field(1) 
	public D3DDISPLAYMODEFILTER Format(ValuedEnum<D3DFORMAT > Format) {
		this.io.setEnumField(this, 1, Format);
		return this;
	}
	/// C type : D3DSCANLINEORDERING
	@Field(2) 
	public ValuedEnum<D3DSCANLINEORDERING > ScanLineOrdering() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : D3DSCANLINEORDERING
	@Field(2) 
	public D3DDISPLAYMODEFILTER ScanLineOrdering(ValuedEnum<D3DSCANLINEORDERING > ScanLineOrdering) {
		this.io.setEnumField(this, 2, ScanLineOrdering);
		return this;
	}
}
