package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DGAMMARAMP extends StructObject {
	public D3DGAMMARAMP() {
		super();
	}
	public D3DGAMMARAMP(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : WORD[256]
	@Array({256}) 
	@Field(0) 
	public Pointer<Short > red() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : WORD[256]
	@Array({256}) 
	@Field(1) 
	public Pointer<Short > green() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : WORD[256]
	@Array({256}) 
	@Field(2) 
	public Pointer<Short > blue() {
		return this.io.getPointerField(this, 2);
	}
}
