package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DLINEPATTERN extends StructObject {
	public D3DLINEPATTERN() {
		super();
	}
	public D3DLINEPATTERN(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public short wRepeatFactor() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public D3DLINEPATTERN wRepeatFactor(short wRepeatFactor) {
		this.io.setShortField(this, 0, wRepeatFactor);
		return this;
	}
	@Field(1) 
	public short wLinePattern() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public D3DLINEPATTERN wLinePattern(short wLinePattern) {
		this.io.setShortField(this, 1, wLinePattern);
		return this;
	}
}
