package com.fourthskyinteractive.dx4j.d3d9.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d9.D3D9.D3DFORMAT;
import com.fourthskyinteractive.dx4j.d3d9.D3D9.D3DMULTISAMPLE_TYPE;
import com.fourthskyinteractive.dx4j.d3d9.D3D9.D3DSWAPEFFECT;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d9") 
public class D3DPRESENT_PARAMETERS extends StructObject {
	public D3DPRESENT_PARAMETERS() {
		super();
	}
	public D3DPRESENT_PARAMETERS(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	@Field(0) 
	public int BackBufferWidth() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public D3DPRESENT_PARAMETERS BackBufferWidth(int BackBufferWidth) {
		this.io.setIntField(this, 0, BackBufferWidth);
		return this;
	}
	@Field(1) 
	public int BackBufferHeight() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public D3DPRESENT_PARAMETERS BackBufferHeight(int BackBufferHeight) {
		this.io.setIntField(this, 1, BackBufferHeight);
		return this;
	}
	/// C type : D3DFORMAT
	@Field(2) 
	public ValuedEnum<D3DFORMAT > BackBufferFormat() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : D3DFORMAT
	@Field(2) 
	public D3DPRESENT_PARAMETERS BackBufferFormat(ValuedEnum<D3DFORMAT > BackBufferFormat) {
		this.io.setEnumField(this, 2, BackBufferFormat);
		return this;
	}
	@Field(3) 
	public int BackBufferCount() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public D3DPRESENT_PARAMETERS BackBufferCount(int BackBufferCount) {
		this.io.setIntField(this, 3, BackBufferCount);
		return this;
	}
	/// C type : D3DMULTISAMPLE_TYPE
	@Field(4) 
	public ValuedEnum<D3DMULTISAMPLE_TYPE > MultiSampleType() {
		return this.io.getEnumField(this, 4);
	}
	/// C type : D3DMULTISAMPLE_TYPE
	@Field(4) 
	public D3DPRESENT_PARAMETERS MultiSampleType(ValuedEnum<D3DMULTISAMPLE_TYPE > MultiSampleType) {
		this.io.setEnumField(this, 4, MultiSampleType);
		return this;
	}
	@Field(5) 
	public int MultiSampleQuality() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public D3DPRESENT_PARAMETERS MultiSampleQuality(int MultiSampleQuality) {
		this.io.setIntField(this, 5, MultiSampleQuality);
		return this;
	}
	/// C type : D3DSWAPEFFECT
	@Field(6) 
	public ValuedEnum<D3DSWAPEFFECT > SwapEffect() {
		return this.io.getEnumField(this, 6);
	}
	/// C type : D3DSWAPEFFECT
	@Field(6) 
	public D3DPRESENT_PARAMETERS SwapEffect(ValuedEnum<D3DSWAPEFFECT > SwapEffect) {
		this.io.setEnumField(this, 6, SwapEffect);
		return this;
	}
	/// C type : HWND
	@Field(7) 
	public Pointer<? > hDeviceWindow() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : HWND
	@Field(7) 
	public D3DPRESENT_PARAMETERS hDeviceWindow(Pointer<? > hDeviceWindow) {
		this.io.setPointerField(this, 7, hDeviceWindow);
		return this;
	}
	@Field(8) 
	public int Windowed() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public D3DPRESENT_PARAMETERS Windowed(int Windowed) {
		this.io.setIntField(this, 8, Windowed);
		return this;
	}
	@Field(9) 
	public int EnableAutoDepthStencil() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public D3DPRESENT_PARAMETERS EnableAutoDepthStencil(int EnableAutoDepthStencil) {
		this.io.setIntField(this, 9, EnableAutoDepthStencil);
		return this;
	}
	/// C type : D3DFORMAT
	@Field(10) 
	public ValuedEnum<D3DFORMAT > AutoDepthStencilFormat() {
		return this.io.getEnumField(this, 10);
	}
	/// C type : D3DFORMAT
	@Field(10) 
	public D3DPRESENT_PARAMETERS AutoDepthStencilFormat(ValuedEnum<D3DFORMAT > AutoDepthStencilFormat) {
		this.io.setEnumField(this, 10, AutoDepthStencilFormat);
		return this;
	}
	@Field(11) 
	public int Flags() {
		return this.io.getIntField(this, 11);
	}
	@Field(11) 
	public D3DPRESENT_PARAMETERS Flags(int Flags) {
		this.io.setIntField(this, 11, Flags);
		return this;
	}
	@Field(12) 
	public int FullScreen_RefreshRateInHz() {
		return this.io.getIntField(this, 12);
	}
	@Field(12) 
	public D3DPRESENT_PARAMETERS FullScreen_RefreshRateInHz(int FullScreen_RefreshRateInHz) {
		this.io.setIntField(this, 12, FullScreen_RefreshRateInHz);
		return this;
	}
	@Field(13) 
	public int PresentationInterval() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public D3DPRESENT_PARAMETERS PresentationInterval(int PresentationInterval) {
		this.io.setIntField(this, 13, PresentationInterval);
		return this;
	}
}
