package com.fourthskyinteractive.dx4j.d3d11.shader;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d3d11.D3D11.D3D_CBUFFER_TYPE;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3dcompiler") 
public class D3D11_SHADER_BUFFER_DESC extends StructObject {
	public D3D11_SHADER_BUFFER_DESC() {
		super();
	}
	public D3D11_SHADER_BUFFER_DESC(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/**
	 * Name of the constant buffer<br>
	 * C type : LPCSTR
	 */
	@Field(0) 
	public Pointer<Byte > Name() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * Name of the constant buffer<br>
	 * C type : LPCSTR
	 */
	@Field(0) 
	public D3D11_SHADER_BUFFER_DESC Name(Pointer<Byte > Name) {
		this.io.setPointerField(this, 0, Name);
		return this;
	}
	/**
	 * Indicates type of buffer content<br>
	 * C type : D3D_CBUFFER_TYPE
	 */
	@Field(1) 
	public ValuedEnum<D3D_CBUFFER_TYPE > Type() {
		return this.io.getEnumField(this, 1);
	}
	/**
	 * Indicates type of buffer content<br>
	 * C type : D3D_CBUFFER_TYPE
	 */
	@Field(1) 
	public D3D11_SHADER_BUFFER_DESC Type(ValuedEnum<D3D_CBUFFER_TYPE > Type) {
		this.io.setEnumField(this, 1, Type);
		return this;
	}
	/// Number of member variables
	@Field(2) 
	public int Variables() {
		return this.io.getIntField(this, 2);
	}
	/// Number of member variables
	@Field(2) 
	public D3D11_SHADER_BUFFER_DESC Variables(int Variables) {
		this.io.setIntField(this, 2, Variables);
		return this;
	}
	/// Size of CB (in bytes)
	@Field(3) 
	public int Size() {
		return this.io.getIntField(this, 3);
	}
	/// Size of CB (in bytes)
	@Field(3) 
	public D3D11_SHADER_BUFFER_DESC Size(int Size) {
		this.io.setIntField(this, 3, Size);
		return this;
	}
	/// Buffer description flags
	@Field(4) 
	public int uFlags() {
		return this.io.getIntField(this, 4);
	}
	/// Buffer description flags
	@Field(4) 
	public D3D11_SHADER_BUFFER_DESC uFlags(int uFlags) {
		this.io.setIntField(this, 4, uFlags);
		return this;
	}
}
