package com.fourthskyinteractive.dx4j.d3d11.shader;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d11") 
public class D3D11_SO_DECLARATION_ENTRY extends StructObject {
	public D3D11_SO_DECLARATION_ENTRY() {
		super();
	}
	public D3D11_SO_DECLARATION_ENTRY(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	public D3D11_SO_DECLARATION_ENTRY(int Stream, String SemanticName, int SemanticIndex, int StartComponent, int ComponentCount, int OutputSlot) {
		super();
		this.Stream(Stream)
			.SemanticName(Pointer.pointerToCString(SemanticName))
			.SemanticIndex(SemanticIndex)
			.StartComponent((byte)StartComponent)
			.ComponentCount((byte)ComponentCount)
			.OutputSlot((byte)OutputSlot);
	}
	@Field(0) 
	public int Stream() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public D3D11_SO_DECLARATION_ENTRY Stream(int Stream) {
		this.io.setIntField(this, 0, Stream);
		return this;
	}
	/// C type : LPCSTR
	@Field(1) 
	public Pointer<Byte > SemanticName() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : LPCSTR
	@Field(1) 
	public D3D11_SO_DECLARATION_ENTRY SemanticName(Pointer<Byte > SemanticName) {
		this.io.setPointerField(this, 1, SemanticName);
		return this;
	}
	@Field(2) 
	public int SemanticIndex() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public D3D11_SO_DECLARATION_ENTRY SemanticIndex(int SemanticIndex) {
		this.io.setIntField(this, 2, SemanticIndex);
		return this;
	}
	@Field(3) 
	public byte StartComponent() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public D3D11_SO_DECLARATION_ENTRY StartComponent(byte StartComponent) {
		this.io.setByteField(this, 3, StartComponent);
		return this;
	}
	@Field(4) 
	public byte ComponentCount() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public D3D11_SO_DECLARATION_ENTRY ComponentCount(byte ComponentCount) {
		this.io.setByteField(this, 4, ComponentCount);
		return this;
	}
	@Field(5) 
	public byte OutputSlot() {
		return this.io.getByteField(this, 5);
	}
	@Field(5) 
	public D3D11_SO_DECLARATION_ENTRY OutputSlot(byte OutputSlot) {
		this.io.setByteField(this, 5, OutputSlot);
		return this;
	}
}
