package com.fourthskyinteractive.dx4j.d3d11.shader;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d11") 
public class D3D_SHADER_MACRO extends StructObject {
	public D3D_SHADER_MACRO() {
		super();
	}
	public D3D_SHADER_MACRO(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : LPCSTR
	@Field(0) 
	public Pointer<Byte > Name() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : LPCSTR
	@Field(0) 
	public D3D_SHADER_MACRO Name(Pointer<Byte > Name) {
		this.io.setPointerField(this, 0, Name);
		return this;
	}
	/// C type : LPCSTR
	@Field(1) 
	public Pointer<Byte > Definition() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : LPCSTR
	@Field(1) 
	public D3D_SHADER_MACRO Definition(Pointer<Byte > Definition) {
		this.io.setPointerField(this, 1, Definition);
		return this;
	}
}
