package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * SOFT BOUNDS ASSUMPTIONS<br>
 * Corners are in clockwise order.<br>
 * Tracking space center (0,0,0) is contained within the Soft Bounds.<br>
 * Angles of corners are between 25 and 155 degrees. <br>
 * Quadrilateral formed is convex. <br>
 * One side will run parallel to the X axis. <br>
 * Height of every corner is 0Y (on the floor).<br>
 * <i>native declaration : /usr/include/stdint.h:1026</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("ChaperoneSoftBoundsInfo_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class ChaperoneSoftBoundsInfo_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : HmdQuad_t */
	@Field(0) 
	public HmdQuad_t quadCorners() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : HmdQuad_t */
	@Field(0) 
	public ChaperoneSoftBoundsInfo_t quadCorners(HmdQuad_t quadCorners) {
		this.io.setNativeObjectField(this, 0, quadCorners);
		return this;
	}
	public ChaperoneSoftBoundsInfo_t() {
		super();
	}
	public ChaperoneSoftBoundsInfo_t(Pointer pointer) {
		super(pointer);
	}
}
