package openvr_api;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * Provides a single frame's timing information to the app<br>
 * <i>native declaration : /usr/include/stdint.h:1092</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("Compositor_FrameTiming") 
@Namespace("vr") 
@Library("openvr_api") 
public abstract class Compositor_FrameTiming extends StructObject {
	static {
		BridJ.register();
	}
	/** sizeof(Compositor_FrameTiming) */
	@Field(0) 
	public int size() {
		return this.io.getIntField(this, 0);
	}
	/** sizeof(Compositor_FrameTiming) */
	@Field(0) 
	public Compositor_FrameTiming size(int size) {
		this.io.setIntField(this, 0, size);
		return this;
	}
	@Field(1) 
	public double frameStart() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public Compositor_FrameTiming frameStart(double frameStart) {
		this.io.setDoubleField(this, 1, frameStart);
		return this;
	}
	/** seconds from frame start */
	@Field(2) 
	public float frameVSync() {
		return this.io.getFloatField(this, 2);
	}
	/** seconds from frame start */
	@Field(2) 
	public Compositor_FrameTiming frameVSync(float frameVSync) {
		this.io.setFloatField(this, 2, frameVSync);
		return this;
	}
	@Field(3) 
	public int droppedFrames() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public Compositor_FrameTiming droppedFrames(int droppedFrames) {
		this.io.setIntField(this, 3, droppedFrames);
		return this;
	}
	@Field(4) 
	public int frameIndex() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public Compositor_FrameTiming frameIndex(int frameIndex) {
		this.io.setIntField(this, 4, frameIndex);
		return this;
	}
	/** Conversion Error : vr::TrackedDevicePose_t (failed to convert type to Java (undefined type)) */
}
