package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * The mesh to draw into the stencil (or depth) buffer to perform <br>
 * early stencil (or depth) kills of pixels that will never appear on the HMD.<br>
 * This mesh draws on all the pixels that will be hidden after distortion. <br>
 * If the HMD does not provide a visible area mesh pVertexData will be<br>
 * NULL and unTriangleCount will be 0.<br>
 * <i>native declaration : /usr/include/stdint.h:610</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("HiddenAreaMesh_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class HiddenAreaMesh_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : const HmdVector2_t* */
	@Field(0) 
	public Pointer<HmdVector2_t > pVertexData() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : const HmdVector2_t* */
	@Field(0) 
	public HiddenAreaMesh_t pVertexData(Pointer<HmdVector2_t > pVertexData) {
		this.io.setPointerField(this, 0, pVertexData);
		return this;
	}
	@Field(1) 
	public int unTriangleCount() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public HiddenAreaMesh_t unTriangleCount(int unTriangleCount) {
		this.io.setIntField(this, 1, unTriangleCount);
		return this;
	}
	public HiddenAreaMesh_t() {
		super();
	}
	public HiddenAreaMesh_t(Pointer pointer) {
		super(pointer);
	}
}
