package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * <i>native declaration : /usr/include/stdint.h:327</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("HmdQuaternion_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class HmdQuaternion_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public double w() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public HmdQuaternion_t w(double w) {
		this.io.setDoubleField(this, 0, w);
		return this;
	}
	@Field(1) 
	public double x() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public HmdQuaternion_t x(double x) {
		this.io.setDoubleField(this, 1, x);
		return this;
	}
	@Field(2) 
	public double y() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public HmdQuaternion_t y(double y) {
		this.io.setDoubleField(this, 2, y);
		return this;
	}
	@Field(3) 
	public double z() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public HmdQuaternion_t z(double z) {
		this.io.setDoubleField(this, 3, z);
		return this;
	}
	public HmdQuaternion_t() {
		super();
	}
	public HmdQuaternion_t(Pointer pointer) {
		super(pointer);
	}
}
