package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * <i>native declaration : /usr/include/stdint.h:322</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("HmdVector2_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class HmdVector2_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : float[2] */
	@Array({2}) 
	@Field(0) 
	public Pointer<Float > v() {
		return this.io.getPointerField(this, 0);
	}
	public HmdVector2_t() {
		super();
	}
	public HmdVector2_t(Pointer pointer) {
		super(pointer);
	}
}
