package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * Used for events about processes<br>
 * <i>native declaration : /usr/include/stdint.h:570</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("VREvent_Process_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class VREvent_Process_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int pid() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public VREvent_Process_t pid(int pid) {
		this.io.setIntField(this, 0, pid);
		return this;
	}
	@Field(1) 
	public int oldPid() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public VREvent_Process_t oldPid(int oldPid) {
		this.io.setIntField(this, 1, oldPid);
		return this;
	}
	public VREvent_Process_t() {
		super();
	}
	public VREvent_Process_t(Pointer pointer) {
		super(pointer);
	}
}
