package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
import org.bridj.ann.Union;
/**
 * <i>native declaration : /usr/include/stdint.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("VREvent_Data_t") 
@Namespace("vr") 
@Union 
@Library("openvr_api") 
public class VREvent_Data_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : VREvent_Reserved_t */
	@Field(0) 
	public VREvent_Reserved_t reserved() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : VREvent_Reserved_t */
	@Field(0) 
	public VREvent_Data_t reserved(VREvent_Reserved_t reserved) {
		this.io.setNativeObjectField(this, 0, reserved);
		return this;
	}
	/** C type : VREvent_Controller_t */
	@Field(1) 
	public VREvent_Controller_t controller() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : VREvent_Controller_t */
	@Field(1) 
	public VREvent_Data_t controller(VREvent_Controller_t controller) {
		this.io.setNativeObjectField(this, 1, controller);
		return this;
	}
	/** C type : VREvent_Mouse_t */
	@Field(2) 
	public VREvent_Mouse_t mouse() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : VREvent_Mouse_t */
	@Field(2) 
	public VREvent_Data_t mouse(VREvent_Mouse_t mouse) {
		this.io.setNativeObjectField(this, 2, mouse);
		return this;
	}
	/** C type : VREvent_Process_t */
	@Field(3) 
	public VREvent_Process_t process() {
		return this.io.getNativeObjectField(this, 3);
	}
	/** C type : VREvent_Process_t */
	@Field(3) 
	public VREvent_Data_t process(VREvent_Process_t process) {
		this.io.setNativeObjectField(this, 3, process);
		return this;
	}
	public VREvent_Data_t() {
		super();
	}
	public VREvent_Data_t(Pointer pointer) {
		super(pointer);
	}
}
