package openvr_api;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * Not actually used for any events. It is just used to reserve<br>
 * space in the union for future event types<br>
 * <i>native declaration : /usr/include/stdint.h:579</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("VREvent_Reserved_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class VREvent_Reserved_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public long reserved0() {
		return this.io.getLongField(this, 0);
	}
	@Field(0) 
	public VREvent_Reserved_t reserved0(long reserved0) {
		this.io.setLongField(this, 0, reserved0);
		return this;
	}
	@Field(1) 
	public long reserved1() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public VREvent_Reserved_t reserved1(long reserved1) {
		this.io.setLongField(this, 1, reserved1);
		return this;
	}
	public VREvent_Reserved_t() {
		super();
	}
	public VREvent_Reserved_t(Pointer pointer) {
		super(pointer);
	}
}
