package openvr_api;
import openvr_api.IOpenvr_api.EVRButtonId;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * used for controller button events<br>
 * <i>native declaration : /usr/include/stdint.h:546</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("VREvent_Controller_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class VREvent_Controller_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : EVRButtonId */
	@Field(0) 
	public IntValuedEnum<EVRButtonId > button() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : EVRButtonId */
	@Field(0) 
	public VREvent_Controller_t button(IntValuedEnum<EVRButtonId > button) {
		this.io.setEnumField(this, 0, button);
		return this;
	}
	public VREvent_Controller_t() {
		super();
	}
	public VREvent_Controller_t(Pointer pointer) {
		super(pointer);
	}
}
