package openvr_api;
import openvr_api.IOpenvr_api.EVRMouseButton;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Namespace;
/**
 * used for simulated mouse events in overlay space<br>
 * <i>native declaration : /usr/include/stdint.h:562</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("VREvent_Mouse_t") 
@Namespace("vr") 
@Library("openvr_api") 
public class VREvent_Mouse_t extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public float x() {
		return this.io.getFloatField(this, 0);
	}
	@Field(0) 
	public VREvent_Mouse_t x(float x) {
		this.io.setFloatField(this, 0, x);
		return this;
	}
	@Field(1) 
	public float y() {
		return this.io.getFloatField(this, 1);
	}
	@Field(1) 
	public VREvent_Mouse_t y(float y) {
		this.io.setFloatField(this, 1, y);
		return this;
	}
	/** C type : EVRMouseButton */
	@Field(2) 
	public IntValuedEnum<EVRMouseButton > button() {
		return this.io.getEnumField(this, 2);
	}
	/** C type : EVRMouseButton */
	@Field(2) 
	public VREvent_Mouse_t button(IntValuedEnum<EVRMouseButton > button) {
		this.io.setEnumField(this, 2, button);
		return this;
	}
	public VREvent_Mouse_t() {
		super();
	}
	public VREvent_Mouse_t(Pointer pointer) {
		super(pointer);
	}
}
