package com.fourthskyinteractive.dx4j.d2d1.resources.rendertarget;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d2d1.D2D1.D2D1_PRESENT_OPTIONS;
import com.fourthskyinteractive.dx4j.d2d1.resources.geometry.D2D1_SIZE_U;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d2d1") 
public class D2D1_HWND_RENDER_TARGET_PROPERTIES extends StructObject {
	public D2D1_HWND_RENDER_TARGET_PROPERTIES() {
		super();
	}
	public D2D1_HWND_RENDER_TARGET_PROPERTIES(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : HWND
	@Field(0) 
	public Pointer<? > hwnd() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : HWND
	@Field(0) 
	public D2D1_HWND_RENDER_TARGET_PROPERTIES hwnd(Pointer<? > hwnd) {
		this.io.setPointerField(this, 0, hwnd);
		return this;
	}
	/// C type : D2D1_SIZE_U
	@Field(1) 
	public D2D1_SIZE_U pixelSize() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : D2D1_SIZE_U
	@Field(1) 
	public D2D1_HWND_RENDER_TARGET_PROPERTIES pixelSize(D2D1_SIZE_U size) {
		this.io.setNativeObjectField(this, 1, size);
		return this;
	}
	/// C type : D2D1_PRESENT_OPTIONS
	@Field(2) 
	public ValuedEnum<D2D1_PRESENT_OPTIONS > presentOptions() {
		return this.io.getEnumField(this, 2);
	}
	/// C type : D2D1_PRESENT_OPTIONS
	@Field(2) 
	public D2D1_HWND_RENDER_TARGET_PROPERTIES presentOptions(ValuedEnum<D2D1_PRESENT_OPTIONS > presentOptions) {
		this.io.setEnumField(this, 2, presentOptions);
		return this;
	}
}
