package com.fourthskyinteractive.dx4j.d2d1.core;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ValuedEnum;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

import com.fourthskyinteractive.dx4j.d2d1.D2D1.D2D1_DEBUG_LEVEL;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d2d1") 
public class D2D1_FACTORY_OPTIONS extends StructObject {
	public D2D1_FACTORY_OPTIONS() {
		super();
	}
	public D2D1_FACTORY_OPTIONS(Pointer<? extends StructObject> pointer) {
		super(pointer);
	}
	/// C type : D2D1_DEBUG_LEVEL
	@Field(0) 
	public ValuedEnum<D2D1_DEBUG_LEVEL > debugLevel() {
		return this.io.getEnumField(this, 0);
	}
	/// C type : D2D1_DEBUG_LEVEL
	@Field(0) 
	public D2D1_FACTORY_OPTIONS debugLevel(ValuedEnum<D2D1_DEBUG_LEVEL > debugLevel) {
		this.io.setEnumField(this, 0, debugLevel);
		return this;
	}
}
